#!/bin/bash
# ------------------------------------------------------------------------------
# Copyright (c) 2016-2023 Advantech Co. Ltd.
# All Rights Reserved
#
# Run kernel pktgen on ethernet devices
# ------------------------------------------------------------------------------

# Script-version-start ---------------------------------------------------------
# !!! This section is generated by standardize.sh, never add content here manually!
ADV_SCRIPT_REVISION="g69"
ADV_SCRIPT_MD5="37b50c06877c9eff7d7ffadaec4828b4"
ADV_SCRIPT_DATE="2023-11-06 09:35:24"
advShowHelp() {
     echo -e "\e[07m"$(basename "$0")" $ADV_SCRIPT_REVISION ($ADV_SCRIPT_DATE)\e[0m"
     echo -e "$ADV_SCRIPT_HELP"
     [ -z $1 ] && exit 0 || exit $1 
}
# !!! This section is generated by standardize.sh, never add content here manually!
# Script-version-end -----------------------------------------------------------

# Basic-functions-start --------------------------------------------------------
# !!! This section is generated by standardize.sh, never add content here manually!
export ADV_SYS_DATE="date +%Y.%m.%d"
export ADV_SYS_TIME="date +%Y.%m.%d-%H.%M.%S"
export ADV_SYS_TIME_STRING="eval date '+%Y.%m.%d %H:%M:%S'"
[[ -z $ADV_TEST_ITEM ]] && ADV_TEST_ITEM="$(basename "$0")"

advGetCurrentPath() {
    local SOURCE="${BASH_SOURCE[0]}"
    while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
        local DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
        SOURCE="$(readlink "$SOURCE")"
        # if $SOURCE was a relative symlink, we need to resolve it relative 
        # to the path where the symlink file was located
        [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" 
    done
    echo $( cd -P "$( dirname "$SOURCE" )" && pwd )
    return 0
}

advToUpper() {
    [[ -z $1 ]] && read INPUT || INPUT="$@"
    echo "$INPUT" | tr [:lower:] [:upper:]
    return 0
}

advToLower() {
    [[ -z $1 ]] && read INPUT || INPUT="$@"
    echo "$INPUT" | tr [:upper:] [:lower:]
    return 0
}

advError() {
    local CONTENT="["`$ADV_SYS_TIME_STRING`"] [ERROR] $@"
    [[ -n $ADV_LOG_TO_PXE_SERVER ]] && logger -t "adv_diag_log" -p user.error "${ADV_LOG_FILE#*/adv_diag_log/} $CONTENT"
    echo -e "\033[31m""$CONTENT""\033[0m" >&2
    [[ -e $ADV_LOG_FILE ]] && echo -e "$CONTENT" >> $ADV_LOG_FILE
    return 0
}

advNotice() {
    local CONTENT="["`$ADV_SYS_TIME_STRING`"] [NOTICE] $@"
    [[ -n $ADV_LOG_TO_PXE_SERVER ]] && logger -t "adv_diag_log" -p user.notice "${ADV_LOG_FILE#*/adv_diag_log/} $CONTENT"
    echo -e "\033[33m""$CONTENT""\033[0m"
    [[ -e $ADV_LOG_FILE ]] && echo -e "$CONTENT" >> $ADV_LOG_FILE
    return 0
}

advInfo() {
    local CONTENT="["`$ADV_SYS_TIME_STRING`"] [INFO] $@"
    [[ -n $ADV_LOG_TO_PXE_SERVER ]] && logger -t "adv_diag_log" -p user.info "${ADV_LOG_FILE#*/adv_diag_log/} $CONTENT"
    echo -e "$CONTENT"
    [[ -e $ADV_LOG_FILE ]] && echo -e "$CONTENT" >> $ADV_LOG_FILE
    return 0
}

advInfof () {
    local FORMAT="%s %s %s $1"
    shift

    printf "${FORMAT}" "["$($ADV_SYS_TIME_STRING)"]" "[INFO]" "$@"

    local CONTENT=$(printf "${FORMAT}" "["$($ADV_SYS_TIME_STRING)"]" "[INFO]" "$@" | sed "s/\x1B\[[0-9;]*[mK]//g")
    [[ -n $ADV_LOG_TO_PXE_SERVER ]] && logger -t "adv_diag_log" -p user.info "${ADV_LOG_FILE#*/adv_diag_log/} $CONTENT"
    [[ -e $ADV_LOG_FILE ]] && echo -e "$CONTENT" >> $ADV_LOG_FILE

    return 0
}

advFailed() {
    local CONTENT="["`$ADV_SYS_TIME_STRING`"] [FAIL] $@"
    [[ -n $ADV_LOG_TO_PXE_SERVER ]] && logger -t "adv_diag_log" -p user.error "${ADV_LOG_FILE#*/adv_diag_log/} $CONTENT"
    echo -e "\033[31m""$CONTENT""\033[0m" >&2
    [[ -e $ADV_LOG_FILE ]] && echo -e "$CONTENT" >> $ADV_LOG_FILE
    return 0
}

advPassed() {
    local CONTENT="["`$ADV_SYS_TIME_STRING`"] [PASS] $@"
    [[ -n $ADV_LOG_TO_PXE_SERVER ]] && logger -t "adv_diag_log" -p user.notice "${ADV_LOG_FILE#*/adv_diag_log/} $CONTENT"
    echo -e "\033[32m""$CONTENT""\033[0m" >&2
    [[ -e $ADV_LOG_FILE ]] && echo -e "$CONTENT" >> $ADV_LOG_FILE
    return 0
}

advRunLog() {
    advInfo "Running: $@"
    "$@" 2>&1 | tee -a "$ADV_LOG_FILE"
    return ${PIPESTATUS[0]}
}

advCheckParam() {
    local TYPE="$1"
    local NAME="$2"
    shift 2

    [[ $TYPE = "unknown" ]] && advError "Unknown parameter: $NAME" && exit 1
    
    local VALUE="$@"
    [[ -z $VALUE ]] && advError "Missing $NAME" && exit 1

    case $TYPE in
        "any")
            PATTERN='.*'
            ;;
        "digit")
            PATTERN='^[0-9]$'
            ;;
        "number")
            PATTERN='^[0-9]+$'
            ;;
        "nlist")
            PATTERN='^[0-9,\-]+$'
            ;;
        nrange-*)
            PATTERN='^[0-9]+$'
            ;;
        "hex")
            PATTERN='^[0-9A-Fa-f]+$'
            ;;
        "float")
            PATTERN='^([0-9]+\.[0-9]+|[0-9]+)$'
            ;;
        "pcie")
            PATTERN='^[0-9A-Fa-f]+:[0-9A-Fa-f]+\.[0-9A-Fa-f]$'
            ;;
        "ip")
            PATTERN='^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$'
            ;;
        *)
            PATTERN="$TYPE"
            ;;
    esac
    if [[ ! "$VALUE" =~ $PATTERN ]]; then
        advError "Invalid $NAME: $VALUE"
        exit 1
    fi
    if [[ "$TYPE" =~ ^nrange-.* ]]; then
        local RANGE_S=`echo "$TYPE" | cut -d '-' -f 2`
        local RANGE_E=`echo "$TYPE" | cut -d '-' -f 3`
        [[ $VALUE -lt $RANGE_S || $VALUE -gt $RANGE_E ]] && advError "Invalid $NAME ($RANGE_S-$RANGE_E): $VALUE" && exit 1
    fi
}

advGetNetPCIEs() {
    local NET_PCIES="`ls -l /sys/class/net/ | grep -oE '/[0-9A-Fa-f:.]+/net' | cut -d '/' -f 2 | sort`"
    [[ -z $1 ]] && echo "$NET_PCIES" && return 0
    echo "$NET_PCIES" | grep "$1:"
    return $?
}

advTrap() {
    local CALLBACK="$1"; shift
    [[ $# -eq 0 ]] && ADV_SIGS=(SIGINT SIGTERM SIGHUP) || ADV_SIGS=($@)
    for sig in ${ADV_SIGS[@]}; do
        trap "advTrapCallback $sig $CALLBACK" "$sig"
    done
}

advNoTrap() {
    [[ $# -ne 0 ]] && ADV_SIGS=($@)
    [[ -z $ADV_SIGS ]] && ADV_SIGS=(SIGINT SIGTERM SIGHUP)
    trap - ${ADV_SIGS[@]}
    unset ADV_SIGS
}

advTrapCallback() {
    advNotice "Cancelling by $1 ..."
    shift
    $@
}
# !!! This section is generated by standardize.sh, never add content here manually!
# Basic-functions-end ----------------------------------------------------------

# Log-functions-start ----------------------------------------------------------
# !!! This section is generated by standardize.sh, never add content here manually!
ADV_TIME_TAG=`$ADV_SYS_TIME`
ADV_SCRIPT_PATH=`advGetCurrentPath`
# If log path is set, use it, otherwise create one
if [[ -z $ADV_OUTPUT_PATH ]]; then
    ADV_OUTPUT_PATH="$HOME/adv_diag_log"
    mkdir -p $ADV_OUTPUT_PATH
    export ADV_OUTPUT_PATH
fi
# If log file is set, use it, otherwise create one
if [[ -z $ADV_LOG_FILE ]]; then
    ADV_LOG_FILE="$ADV_OUTPUT_PATH/`basename "$0"`-$ADV_TIME_TAG.log"
    touch $ADV_LOG_FILE
    export ADV_LOG_FILE
fi
# If adv.pxe.diaglog is set in /proc/cmdline, enable logger
grep -q 'adv.pxe.diaglog' /proc/cmdline
if [[ $? -eq 0 ]]; then
    PXE_SERVER=`grep -oE 'adv\.pxe\.server=[^ ]+' /proc/cmdline | awk -F'=' '{print $2}'`
    [[ -n $PXE_SERVER ]] && export ADV_LOG_TO_PXE_SERVER=$PXE_SERVER
fi
# Log script version
advInfo "$(basename "$0") $ADV_SCRIPT_REVISION ($ADV_SCRIPT_DATE)"
# !!! This section is generated by standardize.sh, never add content here manually!
# Log-functions-end ------------------------------------------------------------

# SymbolLinkCall-functions-start -----------------------------------------------
# !!! This section is generated by standardize.sh, never add content here manually!
ADV_SLN_CALL_NAME=$(basename "$0")
ADV_SCRIPT_ME="$(basename "$(test -L "$0" && readlink "$0" || echo "$0")")"
ADV_SCRIPT_ME=${ADV_SCRIPT_ME%.sh}
if [[ "$ADV_SLN_CALL_NAME" =~ .*_$ADV_SCRIPT_ME\.sh_.* ]]; then
    export PATH=$PATH:$ADV_SCRIPT_PATH
    advInfo "Calling from symbol link $ADV_SLN_CALL_NAME ..."
    PARAMS=${ADV_SLN_CALL_NAME#*$ADV_SCRIPT_ME.sh_}
    PARAMS=${PARAMS//__/+}
    PARAMS=${PARAMS//_/ }
    PARAMS=${PARAMS//+/_}
    advNotice "Redirecting to run: $ADV_SCRIPT_ME.sh $PARAMS"
    export ADV_TEST_ITEM=$ADV_SLN_CALL_NAME
    $ADV_SCRIPT_ME.sh $PARAMS
    exit
fi
[[ -z $ADV_TEST_ITEM ]] && ADV_TEST_ITEM="$(basename "$0")"
# !!! This section is generated by standardize.sh, never add content here manually!
# SymbolLinkCall-functions-end ------------------------------------------------------------

# pktgen function from here ----------------------------------------------------
pgset() {
    local result
    [[ -n $VERBOSE_MODE ]] && advInfo "pgset: $2 > $1"
    echo $2 > $1
    result=`cat $1 | fgrep "Result: OK:"`
    if [ "$result" = "" ]; then
        cat $1 | fgrep Result:
        return 1
    else
        return 0
    fi
}
# pktgen function end ----------------------------------------------------------

advResult() {
    local CONTENT="$@"
    echo -e "$CONTENT"
    [[ -e $ADV_LOG_FILE ]] && echo -e "$CONTENT" >> $ADV_LOG_FILE
}

declare -A matrix_ini_pkts
declare -A matrix_pkts
declare -A matrix_result

advInitialCounter() {
    num_rows=${#ETHS[@]}
    advInfo "Initial statistic counters:"
    advResult "`printf "% 8s % 12s % 8s % 12s % 8s % 8s" NIC TXPKTs TXErrs RXPKTs RXErrs RXCRCs`"
    for ((i=0;i<num_rows;i++)) do
        matrix_ini_pkts[$i,0]=`cat /sys/class/net/${ETHS[i]}/statistics/tx_packets`
        matrix_ini_pkts[$i,1]=`cat /sys/class/net/${ETHS[i]}/statistics/tx_errors`                    
        matrix_ini_pkts[$i,2]=`cat /sys/class/net/${ETHS[i]}/statistics/rx_packets`
        matrix_ini_pkts[$i,3]=`cat /sys/class/net/${ETHS[i]}/statistics/rx_errors`
        matrix_ini_pkts[$i,4]=`cat /sys/class/net/${ETHS[i]}/statistics/rx_crc_errors`
        LINE=`printf "% 8s % 12d % 8d % 12d % 8d % 8d" \
            ${ETHS[i]} ${matrix_ini_pkts[$i,0]} ${matrix_ini_pkts[$i,1]} ${matrix_ini_pkts[$i,2]} ${matrix_ini_pkts[$i,3]} ${matrix_ini_pkts[$i,4]}`
        advResult "$LINE"
    done            
}

advUpdateCounter() {
    num_rows=${#ETHS[@]}
    for ((i=0;i<num_rows;i++)) do
        matrix_pkts[$i,0]=`cat /sys/class/net/${ETHS[i]}/statistics/tx_packets`
        matrix_pkts[$i,1]=`cat /sys/class/net/${ETHS[i]}/statistics/tx_errors`                    
        matrix_pkts[$i,2]=`cat /sys/class/net/${ETHS[i]}/statistics/rx_packets`
        matrix_pkts[$i,3]=`cat /sys/class/net/${ETHS[i]}/statistics/rx_errors`
        matrix_pkts[$i,4]=`cat /sys/class/net/${ETHS[i]}/statistics/rx_crc_errors`
    done

    [[ -z $VERBOSE_MODE ]] && return
    
    advInfo "Current statistic counters:"
    advResult "`printf "% 8s % 12s % 8s % 12s % 8s % 8s" NIC TXPKTs TXErrs RXPKTs RXErrs RXCRCs`"
    for ((i=0;i<num_rows;i++)) do
        LINE=`printf "% 8s % 12d % 8d % 12d % 8d % 8d" \
            ${ETHS[i]} ${matrix_ini_pkts[$i,0]} ${matrix_ini_pkts[$i,1]} ${matrix_ini_pkts[$i,2]} ${matrix_ini_pkts[$i,3]} ${matrix_ini_pkts[$i,4]}`
        advResult "$LINE"
        LINE=`printf "% 8s % 12d % 8d % 12d % 8d % 8d" \
            ${ETHS[i]} ${matrix_pkts[$i,0]} ${matrix_pkts[$i,1]} ${matrix_pkts[$i,2]} ${matrix_pkts[$i,3]} ${matrix_pkts[$i,4]}`
        advResult "\033[36m$LINE\033[0m"
    done
}

ADV_SCRIPT_HELP="Run kernel pktgen on ethernet devices
Usage: "$(basename "$0")" [Options] devices
Options:
    -P <IPv4-Snd-byte>  assigned the second byte number of IPv4 class A IP(10.P.x.x).
                        if set \"h\" or \"host\", using the number of HOSTNAME.
    -b <core-list>      bind cpu core, seprated by comma, like '3,4,5', one core per device
    -j <jumbo-size>     set mtu (for jumbo frame) size
    -w <throughput>     check throughput tolerence in percent (%)
    -p <packet-size>    packet size, default to 1024 bytes.
    -n <packet-to-send> number of packets to send, 
                        0 means for continious sends untill explicitl stopped, default to 0.
    -t <time-to-run>    time to run, in seconds
    -c <copies-of-same> number of copies of the same packet, 0 means all same, default to 0.
    -d <delay>          delay to hard_start_xmit() in nanoseconds, default to 3000.
    -f <flows>          flows in pktgen, default to 8192.
    -l <flowlen>        flowlen in pktgen, default to 8.
    -e <tolerance>      config the PKT lost tolerence in percent (%), default to 5.
    -x                  check tx/rx/crc errors and no error allowed
    -x<number>          check tx/rx/crc errors and <num> error(s) allowed
    -x<percent>%        check tx/rx/crc errors and <percent>% error(s) allowed
    -m <mode>           how to set target ip/mac and check result, 
                        can be \"loop\"/\"l\" or \"host\"/\"h\", or a number, 
                        default to loop mode, 
                        \"none\"/\"n\" means not set target ip/mac.
    -r <interval>       refresh current statistic every <interval> seconds, 
                        0 means don't show, default to 0
    -s <devices>        run these ports in single port loopback mode
                        means each in these ports is tx-rx self loopback
                        other ports are in mode specidifed by -m
    -q                  using random queue map to avoid lock cpu core
    -k                  run celo to enable external loopback
    -a                  force ignore PCIe BDF check and mapping for non-x86 platform
    -v                  run in verbose mode
Mode:
    \"loop\"/\"l\"      means ports are connected in external loopback in pair of single blade.
    \"host\"/\"h\"      means ports are connected to the other blade, and 
                        if hostname ended with a slot number and less than 256,THIS is always number.
                        if hostname ended with a slot number and greater than 256,THIS is always remainder 256.
                        if hostname not ended with a slot number ,THIS is always last two bits of MAC address. 
    \"none\"/\"n\"      means no rule and no IP/MAC setting.
    \"original\"/\"o\"  means ports are connected in external loopback in pair of single blade with original MAC.
    \"chassis\"/\"c\"   means ports are connected in external loopback in pair of single blade, 
                        if hostname ended with a slot number and less than 256,THIS is always number.
                        if hostname ended with a slot number and greater than 256,THIS is always remainder 256.
                        if hostname not ended with a slot number ,THIS is always last two bits of MAC address.
    number              means local ip/mac will be calculated by this number.
    local ip rule       local ip will be calculated by formula: 10.BUS.100+FUNCTION.THIS
                        BUS and FUNCTION is feteched from PCIe bus info.
                        in loop mode, THIS is always 1;
                        in host mode, if tail number of hostname is less than 256, THIS is always tail number.
                        if tail number is greater than 256,THIS is always remainder 256.
                        if hostname not ended with a slot number ,THIS is always last two bits of MAC address.
                        in number mode, THIS is the parameter.
    target ip rule      target ip will be calculated base on local ip.
                        in loop mode, target ip will be set to ip of next port if current is odd, 
                        and ip of previous port if current is even;
                        in host or number mode, target ip will be set to THIS+1 if current is odd, 
                        and THIS-1 if current is even;
    local mac rule      local mac will be calculated by formula: 74:FE:48:BUS:FUNCTION:THIS
                        BUS and FUNCTION is feteched from PCIe bus info.
                        in loop mode, THIS is always 1;
                        in host mode, if tail number of hostname is less than 256, THIS is always tail number.
                        if tail number is greater than 256,THIS is always remainder 256.
                        if hostname not ended with a slot number ,THIS is always last two bits of MAC address.
                        in number mode, THIS is the parameter.
    target mac rule     target mac will be calculated base on local mac.
                        in loop mode, target mac will be set to mac of next port if current is odd, 
                        and mac of previous port if current is even;
                        in host or number mode, target mac will be set to THIS+1 if current is odd, 
                        and THIS-1 if current is even;
Devices:
    all         all ethernet devices
    <if-name>   interface name, like eth0, io0
    <pcie-bus>  signle PCIe bus like 03:00.0
                or leading pattern, like 03, means 03:00.0 03:00.1 03:00.2 and so on
    ~<if-name>  see below
    ~<pcie-bus> filtering PCIe devices and interfaces, usually used with 'all'
                ~b5: remove all devices that BDF matches 'b5'
                ~68:00: remove all devices that BDF matches '68:00'
                ~66:00.0: remove device that BDF is '66:00.0'
                ~b02p0: remove interface which is named 'b02p0'
    PCIe B:D.F is not available for some non-x86 platform, please use '-a' to igore BDF mapping.
Example:
    "$(basename "$0")" -p 64 fi0 eth2 07:00.0 03
    "$(basename "$0")" all ~b5 ~68:00 ~66:00.0 ~66:00.1 ~b02p0
Devices in current system:
""`lspci | grep Ethernet`"
[[ -z $1 ]] && advShowHelp
[[ "$1" = "-h" || "$1" = "--help" ]] && advShowHelp

THIS_COUNT=0
THIS_PACKET_SIZE=1024
THIS_CLONE_SKB=0
THIS_DEPLAY=3000
THIS_FLOWS=8192
THIS_FLOWLEN=8
THIS_PKT_LOST_PER=5
THIS_REFRESH=0
TEST_MODE="loop"
LOCAL_THIS=1
unset THIS_TIME_TO_RUN
while [[ $# -gt 0 ]]; do
    case $1 in
        "-P")
            IPbase=$2
            if [[ "$IPbase" == "h" || "$IPbase" == "host" ]]; then
                advCheckParam '([0-9]|\-)+' "HOSTNAME" $(hostname)
                IPbase=$(hostname | sed -e 's/\([a-zA-Z\]\)*//g')
                IPbase=$(echo $IPbase | awk -F'-' 'BEGIN{sum=0}{for(i=1;i<=NF;i++) sum+=$i}END{print sum}')
            fi
            advCheckParam number "IP base" "$IPbase"
            THIS_IPBASE=${IPbase}
            shift
            ;;
        "-b")
            advCheckParam nlist "cpu core list" "$2"
            THIS_CORES=(${2//,/ })
            shift
            ;;
#        "-i")
#            THIS_MASK_IRQ=1
 #           ;;
        "-w")
            advCheckParam number "throughput" "$2"
            THIS_CHECK_THROUGHPUT=$2
            shift
            ;;
        "-j")
            advCheckParam number "mtu size" "$2"
            THIS_MTU_SIZE=$2
            shift
            ;;
        "-p")
            advCheckParam number "packet size" "$2"
            THIS_PACKET_SIZE=$2
            shift
            ;;
        "-n")
            advCheckParam number "number of packets to send" "$2"
            THIS_COUNT=$2
            shift
            ;;
        "-t")
            advCheckParam number "seconds to run" "$2"
            THIS_TIME_TO_RUN=$2
            shift
            ;;
        "-c")
            advCheckParam number "number of copies of the same packet" "$2"
            THIS_CLONE_SKB=$2
            shift
            ;;
        "-d")
            advCheckParam number "delay nanoseconds" "$2"
            THIS_DEPLAY=$2
            shift
            ;;
        "-f")
            advCheckParam number "flow" "$2"
            THIS_FLOWS=$2
            shift
            ;;
        "-l")
            advCheckParam number "flowlen" "$2"
            THIS_FLOWLEN=$2
            shift
            ;;
        "-e")
            advCheckParam number "error torrelance percent (%)" "$2"
            THIS_PKT_LOST_PER=$2
            shift
            ;;
        "-a")
            THIS_NO_PCIE=1
            ;;
        "-x")
            THIS_NO_ERR_ALLOWED=1
            ;;
        -x*)
            THIS_ERR_ALLOWED=${1:2}
            if [[ $THIS_ERR_ALLOWED =~ ^[0-9]+$ ]]; then
                advNotice "Allow $THIS_ERR_ALLOWED tx/rx error(s)"
            elif [[ $THIS_ERR_ALLOWED =~ ^[0-9]+%$ ]]; then
                THIS_ERR_ALLOWED_PCT=${THIS_ERR_ALLOWED%?}
                unset THIS_ERR_ALLOWED
                advNotice "Allow $THIS_ERR_ALLOWED_PCT% tx/rx error(s)"
            else
               advError "Unknown number/percentage of tx/rx error: $1"
               exit 1 
            fi
            ;;
        "-q")
            THIS_QUEUE_MAP_RND=1
            ;;
        "-k")
            THIS_RUN_CELO=1
            ;;
        "-m")
            advCheckParam any "mode" "$2"
            if [[ "$2" =~ [0-9]+ ]]; then
                TEST_MODE="number"
                LOCAL_THIS=$2
            elif [[ "$2" == "n" || "$2" == "none" ]]; then
                unset TEST_MODE
                unset LOCAL_THIS
            elif [[ "$2" == "l" || "$2" == "loop" ]]; then
                TEST_MODE="loop"
                LOCAL_THIS=1
            elif [[ "$2" == "h" || "$2" == "host" ]]; then
                TEST_MODE="host"
                HOST_NAME=`hostname`
                if [[ "$HOST_NAME" =~ [0-9]+$ ]]; then
                    LOCAL_THIS=`echo $HOST_NAME | grep -oE "[0-9]+$"`
                    LOCAL_THIS=${LOCAL_THIS#0}
                    if [[ $LOCAL_THIS -gt 256 ]]; then
                        let "LOCAL_THIS=LOCAL_THIS%256"
                    fi
                else
                    advError "Hostname is not end with a number"
                    LOCAL_MAC_HEX=` ethtool -P $3 | awk '{print $3}'`                                                         
                    LOCAL_MAC_HEX_LOW=${LOCAL_MAC_HEX:(-2)}                                                                   
                    LOCAL_THIS=`printf "%d" 0x$LOCAL_MAC_HEX_LOW`
                 fi
            elif [[ "$2" == "c" || "$2" == "chassis" ]]; then
                TEST_MODE="loop"
                HOST_NAME=`hostname`
                if [[ "$HOST_NAME" =~ [0-9]+$ ]]; then
                    LOCAL_THIS=`echo $HOST_NAME | grep -oE "[0-9]+$"`
                    LOCAL_THIS=${LOCAL_THIS#0}
                    if [[ $LOCAL_THIS -gt 256 ]]; then
                        let "LOCAL_THIS=LOCAL_THIS%256"
                    fi
                else
                    advError "Hostname is not end with a number"
                    LOCAL_MAC_HEX=` ethtool -P $3 | awk '{print $3}'`                                                         
                    LOCAL_MAC_HEX_LOW=${LOCAL_MAC_HEX:(-2)}   
                    LOCAL_THIS=`printf "%d" 0x$LOCAL_MAC_HEX_LOW`
                fi
            elif [[ "$2" == "o" || "$2" == "original" ]]; then
                TEST_MODE="original"
                HOST_NAME=`hostname`
                if [[ "$HOST_NAME" =~ [0-9]+$ ]]; then
                    LOCAL_THIS=`echo $HOST_NAME | grep -oE "[0-9]+$"`
                    LOCAL_THIS=${LOCAL_THIS#0}
                    if [[ $LOCAL_THIS -gt 256 ]]; then
                        let "LOCAL_THIS=LOCAL_THIS%256"
                    fi
                else
                    advError "Hostname is not end with a number"
                    LOCAL_THIS=1
                fi
            else
                advError "$2 is not a valid mode" && exit 1
            fi
            shift
            ;;
        "-r")
            advCheckParam number "refresh interval" "$2"
            [[ "$2" =~ [0-9]+ ]] || ( advError "$2 is not a valid refresh interval" && exit 1 )
            THIS_REFRESH=$2
            shift
            ;;
        "-s")
            for ITEM in $2; do
                if [[ "$ITEM" == "all" ]]; then
                    SLP_PCIES=(`advGetNetPCIEs`)
                elif [[ "$ITEM" =~ ^[0-9A-Fa-f]+$ ]]; then
                    PCIED=(`advGetNetPCIEs "$ITEM"`)
                    [[ -z $PCIED ]] && advError "Can not found PCIe Ethernet device with leading pattern: $ITEM" && exit 1
                    SLP_PCIES=(${SLP_PCIES[@]} ${PCIED[@]})
                elif [[ "$ITEM" =~ ^[0-9A-Fa-f]+:[0-9A-Fa-f]+\.[0-9A-Fa-f]$ ]]; then
                    SLP_PCIES=(${SLP_PCIES[@]} "$ITEM")
                else
                    PCIED=(`lspci | grep -i "$ITEM" | awk '{print $1}'`)
                    if [[ -n $PCIED ]]; then
                        PCIES=(${PCIES[@]} ${PCIED[@]})
                    else
                        ethtool $ITEM >/dev/null 2>&1
                        [[ $? -ne 0 ]] && advError "Unknown device: $ITEM" && exit 1
                        SLP_ETHS=(${SLP_ETHS[@]} $ITEM)
                    fi
                fi
            done
            if [[ -n $SLP_PCIES ]]; then
                advInfo "Detecting ${SLP_PCIES[@]} ..."
                # Convert pci to eth
                for PCI in ${SLP_PCIES[@]}; do
                    PCI=`ls -l /sys/class/net/ | grep -oE "$PCI/net/.*"`
                    [[ $? -ne 0 ]] && advError "$PCI is not a valid PCIe Ethernet device" && exit 1
                    
                    ETH=${PCI##*/net/}
                    [[ -z $ETH ]] && advError "Can not found PCIe Ethernet device for $PCI" && exit 1
                    SLP_ETHS=(${SLP_ETHS[@]} $ETH)
                done
            fi
            
            [[ -z $SLP_ETHS ]] && advError "No devices selected for single loopback mode!" && exit 1
            
            for ETH in ${SLP_ETHS[@]}; do
                eval SLP_$ETH=1
            done

            shift
            ;;
        "-v")
            VERBOSE_MODE=1
            ;;
        ~*)
            BL="${1:1}"
            if [[ "$BL" =~ ^[0-9A-Fa-f:\.]+$ ]]; then
                advInfo "Filtering Ethernet PCIe device with BDF blacklist $BL ..."
            else
                ETHIF="$BL"
                BL=`ls -l /sys/class/net/ | grep -w "$ETHIF"$ | grep -oE '/[0-9A-Fa-f:.]+/net' | cut -d '/' -f 2`
                advInfo "Filtering Ethernet PCIe device with blacklist $BL($ETHIF) ..."
            fi
            [[ -z $BL ]] && advError "Invalid blacklist!" && exit 1
            PCIED=(${PCIES[@]})
            unset PCIES
            for PCI in ${PCIED[@]}; do
                echo BL=$BL
                echo "$PCI" | grep -i "$BL"
                echo "$PCI" | grep -iq "$BL"
                [[ $? -eq 0 ]] && continue
                PCIES=(${PCIES[@]} "$PCI")
            done
            ;;
        *)
            if [[ "$1" == "all" ]]; then
                PCIES=(`advGetNetPCIEs`)
            elif [[ "$1" =~ ^[0-9A-Fa-f]+$ ]]; then
                PCIED=(`advGetNetPCIEs "$1"`)
                [[ -z $PCIED ]] && advError "Can not found PCIe Ethernet device with leading pattern: $1" && exit 1
                PCIES=(${PCIES[@]} ${PCIED[@]})
            elif [[ "$1" =~ [0-9A-Fa-f]+:[0-9A-Fa-f]+\.[0-9A-Fa-f] ]]; then
                PCIES=(${PCIES[@]} "$1")
            else
                PCIED=(`lspci | grep -i "$1" | awk '{print $1}'`)
                if [[ -n $PCIED ]]; then
                    PCIES=(${PCIES[@]} ${PCIED[@]})
                else
                    ethtool $1 >/dev/null 2>&1
                    [[ $? -ne 0 ]] && advCheckParam unknown "$1"
                    ETHS=(${ETHS[@]} $1)
                fi
            fi
            ;;  
    esac
    
    shift
done

[[ -n $THIS_NO_PCIE && -n $PCIES ]] && advError "PCIe detecting is not available when -a is set!" && exit 1
    
if [[ -n $PCIES ]]; then
    advInfo "Detecting ${PCIES[@]} ..."
    # Convert pci to eth
    for PCI in ${PCIES[@]}; do
        PCI=`ls -l /sys/class/net/ | grep -oE "$PCI/net/.*"`
        [[ $? -ne 0 ]] && advError "$PCI is not a valid PCIe Ethernet device" && exit 1
        
        ETH=${PCI##*/net/}
        [[ -z $ETH ]] && advError "Can not found PCIe Ethernet device for $PCI" && exit 1
        ETHS=(${ETHS[@]} $ETH)
    done
fi

ETHS=(${ETHS[@]} ${SLP_ETHS[@]})

[[ -z $ETHS ]] && advError "No devices selected!" && exit 1

advInfo "Loading pktgen kernel module ..."
modprobe pktgen
[[ $? -ne 0 ]] && advError "Can not load pktgen module!" && exit 1

PKTGEN_PATH="/proc/net/pktgen"
CORE_COUNT=`ls -l /proc/net/pktgen/ | grep kpktgend_ | wc -l`
for CORE in ${THIS_CORES[@]}; do
    if [[ $CORE -ge $CORE_COUNT ]]; then
        advNotice "Core $CORE not exist"
        exit 1
    fi
done

# Generate PCIe bus info
unset PCIES
for ETH in ${ETHS[@]}; do
    if [[ -n $THIS_NO_PCIE ]]; then
        # For non-x86 non-PCIe NICs
        NIC_N=`ls /sys/class/net/ | grep -nwE "$ETH\$"`
        [[ $? -ne 0 ]] && advError "$ETH is not found in /sys/class/net" && exit 1
        NIC_N=`echo "$NIC_N" | cut -d ':' -f 1`
        NIC_N=$((NIC_N-1))
        PCI="ee:00.$NIC_N"
    else
        # For x86 PCIe NICs
        PCI=`ls -l /sys/class/net/ | grep -oE "/[0-9A-Fa-f:.]+/net/$ETH\$"`
        [[ $? -ne 0 ]] && advError "$ETH is not a valid PCIe Ethernet device" && exit 1
    fi
    
    PCI_N=${PCI%%/net/$ETH}
    PCI_N=${PCI_N#/0000:}
    PCIES=(${PCIES[@]} "$PCI_N")
    PCI_N=${PCI_N#0}
    ETH_BUSES=(${ETH_BUSES[@]} ${PCI_N%%:*})
    ETH_FUNCS=(${ETH_FUNCS[@]} ${PCI_N##*.})
done

advRestoreMAC() {
    for ETH in ${ETHS[@]}; do
        CURRENT_MAC=`ip link show dev $ETH | grep ether | awk '{print $2}'`
        PERMANENT_MAC=`ethtool -P $ETH | awk '{print $3}'`
        if [[ "$PERMANENT_MAC" != "$CURRENT_MAC" ]]; then
            advInfo "Restoring MAC of $ETH from $CURRENT_MAC to $PERMANENT_MAC ..."
            if [[ -z $THIS_NO_PCIE ]]; then
                advRunLog ip link set dev $ETH address $PERMANENT_MAC
            else
                advRunLog ifconfig $ETH down
                advRunLog ifconfig $ETH hw ether $PERMANENT_MAC
            fi
        fi
        
        eval ORG_MTU_SIZE=\$ORG_MTU_SIZE_$ETH
        if [[ -n $ORG_MTU_SIZE ]]; then
            advInfo "Restoring MTU of $ETH to $ORG_MTU_SIZE ..."
            advRunLog ip link set dev $ETH mtu $ORG_MTU_SIZE
        fi

        nmcli d show lo | grep -w GENERAL.STATE | grep -wq unmanaged
        if [[ $? -eq 0 ]]; then
            advInfo "Restoring $ETH to be managed by NetworkManager ..."
            advRunLog nmcli dev set $ETH managed yes
        fi
    done
    
    [[ -n $1 ]] && exit $1
    return 0
}

advTrap "advRestoreMAC 1"

if [[ -n $TEST_MODE ]]; then
    advInfo "Configuring IP/MAC on ${ETHS[@]} ..."
    for (( I=0; I<${#ETHS[@]}; I++ )); do
              # Set local mac
        if [[ "$TEST_MODE" == "original" ]]; then
            LOCAL_MAC=`ethtool -P ${ETHS[I]} | awk '{print $3}'`
            advInfo "${ETHS[I]} MAC is $LOCAL_MAC ..."
            ETH_MACS=(${ETH_MACS[@]} $LOCAL_MAC)
        else
            HEX4=`printf "%02X" $((0x${ETH_BUSES[I]}))`
            HEX5=`printf "%02X" $((0x${ETH_FUNCS[I]}))`
            HEX6=`printf "%02X" $LOCAL_THIS`
            LOCAL_MAC="74:FE:48:$HEX4:$HEX5:$HEX6"
            eval IS_SLP=\$SLP_${ETHS[I]}
            if [[ $IS_SLP -eq 0 ]]; then
                advInfo "Setting ${ETHS[I]} MAC to $LOCAL_MAC ..."
                if [[ -z $THIS_NO_PCIE ]]; then
                    advRunLog ip link set dev ${ETHS[I]} address $LOCAL_MAC
                else
                    advRunLog ifconfig ${ETHS[I]} down
                    advRunLog ifconfig ${ETHS[I]} hw ether $LOCAL_MAC
                fi
                [[ $? -ne 0 ]] && advError "Failed to set mac for ${ETHS[I]}: $LOCAL_MAC" && advRestoreMAC 1
            fi
            ETH_MACS=(${ETH_MACS[@]} $LOCAL_MAC)
        fi
        
        # Set local ip
        if [[ -z $THIS_IPBASE ]]; then
            BUS_DEC=`printf "%d" 0x${ETH_BUSES[I]}`
            LOCAL_IP="10.$BUS_DEC.$((100+0x${ETH_FUNCS[I]})).$LOCAL_THIS"
        else
            THIS_IPBASE=$((THIS_IPBASE%254))
            LOCAL_IP="10.$THIS_IPBASE.$((100+0x${ETH_FUNCS[I]})).$LOCAL_THIS"
        fi
        advInfo "Setting ${ETHS[I]} IP to $LOCAL_IP/24 ..."
        advRunLog ip addr del $LOCAL_IP/24 dev ${ETHS[I]}
        advRunLog ip addr add $LOCAL_IP/24 dev ${ETHS[I]}
        [[ $? -ne 0 ]] && advError "Failed to set ip for ${ETHS[I]}: $LOCAL_IP" && advRestoreMAC 1
        ETH_IPS=(${ETH_IPS[@]} $LOCAL_IP)
        
        if [[ -n $THIS_MTU_SIZE ]]; then
            ORG_MTU_SIZE=`ip link show dev ${ETHS[I]} | grep -oE 'mtu [0-9]+' | cut -d ' ' -f 2`
            advInfo "Setting ${ETHS[I]} mtu size from $ORG_MTU_SIZE to $THIS_MTU_SIZE ..."
            advRunLog ip link set dev ${ETHS[I]} mtu $THIS_MTU_SIZE
            eval export ORG_MTU_SIZE_${ETHS[I]}=$ORG_MTU_SIZE
        fi
    done
fi

advInfo "Disabling NetworkManager on ${ETHS[@]} ..."
for (( I=0; I<${#ETHS[@]}; I++ )); do
    advInfo "Set ${ETHS[I]} to be unmanaged by NetworkManager ..."
    advRunLog nmcli dev set ${ETHS[I]} managed no
done

advInfo "Set devices link up ..."
for (( I=0; I<${#ETHS[@]}; I++ )); do
    advRunLog ip link set ${ETHS[I]} up
    [[ -n $THIS_NO_PCIE ]] && advRunLog ifconfig ${ETHS[I]} up
done
if [[ -n $THIS_NO_PCIE ]]; then
    advInfo "Waiting 15 seconds for link up ..."
    sleep 15
fi

CORES_STRING=" ${THIS_CORES[@]} "
for (( I=0; I<CORE_COUNT; I++ )); do
    CORE_ALL=(${CORE_ALL[@]} $I)
    [[ "$CORES_STRING" =~ " $I " ]] || CORE_RESTS=(${CORE_RESTS[@]} $I)
done
CORE_CADIDATES=(${CORE_RESTS[@]})
CORE_RESTS_COUNT=${#CORE_CADIDATES[@]}

advInfo "Resetting all pktgen devices ..."
for CORE in ${CORE_ALL[@]}; do
    pgset $PKTGEN_PATH/kpktgend_$CORE "rem_device_all"
    echo -n "."
done
echo

advInitialCounter

advInfo "Running pktgen on ${ETHS[@]} ..."

for (( I=0; I<${#ETHS[@]}; I++ )); do
    ETH=${ETHS[I]}
    LINK_SPEEDS=(${LINK_SPEEDS[@]} "`ethtool $ETH | grep -E -o "Speed: [0-9]+" | awk '{print $2}'`")

    if [[ -z $THIS_CORES ]]; then
        R=`od -An -N1 -i /dev/random`
        let R=R%CORE_RESTS_COUNT
        CORE=${CORE_RESTS[R]}
        CORE_RESTS=(${CORE_RESTS[@]:0:$R} ${CORE_RESTS[@]:$(($R + 1))})
        CORE_RESTS_COUNT=${#CORE_RESTS[@]}
        if [[ $CORE_RESTS_COUNT -eq 0 ]]; then
            CORE_RESTS=(${CORE_CADIDATES[@]})
            CORE_RESTS_COUNT=${#CORE_RESTS[@]}
        fi
    else
        CORE=${THIS_CORES[0]}
        THIS_CORES=(${THIS_CORES[@]:1})
    fi
    
    advInfo "Binding ${PCIES[I]}($ETH) to kpktgend_$CORE ..."
    
    DEVICES=(${DEVICES[@]} $CORE)
    DEVICE=$PKTGEN_PATH/kpktgend_$CORE
    pgset $DEVICE "add_device $ETH@$CORE"

    DEVICE=$PKTGEN_PATH/$ETH@$CORE
    pgset $DEVICE "count $THIS_COUNT"
    pgset $DEVICE "clone_skb $THIS_CLONE_SKB"
    pgset $DEVICE "pkt_size $THIS_PACKET_SIZE"
    pgset $DEVICE "delay $THIS_DEPLAY"
    pgset $DEVICE "flows $THIS_FLOWS"
    pgset $DEVICE "flowlen $THIS_FLOWLEN" 
    pgset $DEVICE "flag IPSRC_RND"
    pgset $DEVICE "flag UDPSRC_RND"
    pgset $DEVICE "udp_src_min 100"
    pgset $DEVICE "udp_src_max 164"
    pgset $DEVICE "udp_dst_min 100"
    pgset $DEVICE "udp_dst_max 164"
    if [[ -n $THIS_QUEUE_MAP_RND ]]; then
        pgset $DEVICE "flag QUEUE_MAP_RND"
        pgset $DEVICE "flag QUEUE_MAP_CPU"
    fi
    
    if [[ -n $TEST_MODE ]]; then
        SOURCE_MAC=${ETH_MACS[I]}
        SOURCE_IP=${ETH_IPS[I]}

        eval IS_SLP=\$SLP_$ETH
        if [[ $IS_SLP -eq 0 ]]; then
            let R=I%2
            if [[ "$TEST_MODE" == "loop" || "$TEST_MODE" == "original" ]]; then
                [[ $R -eq 0 ]] && let T=I+1 || let T=I-1
                TARGET_MAC=${ETH_MACS[T]}
                TARGET_IP=${ETH_IPS[T]}
            else
                [[ $R -eq 0 ]] && let TARGET_THIS=LOCAL_THIS-1 || let TARGET_THIS=LOCAL_THIS+1
                HEX4=`printf "%02X" 0x${ETH_BUSES[I]}`
                HEX5=`printf "%02X" 0x${ETH_FUNCS[I]}`
                HEX6=`printf "%02X" $TARGET_THIS`
                TARGET_MAC="74:FE:48:$HEX4:$HEX5:$HEX6"
                TARGET_IP="10.$((0x${ETH_BUSES[I]})).$((100+0x${ETH_FUNCS[I]})).$TARGET_THIS"
            fi
            
            advInfo "Disabling promisc mode ..."
            advRunLog ip link set $ETH promisc off
        else
            TARGET_MAC=$SOURCE_MAC
            TARGET_IP=$SOURCE_IP
            
            if [[ -n $THIS_RUN_CELO ]]; then
                advInfo "Run celo ${PCIES[I]}($ETH) to enable external loopback ..."
                PCIE_A="${PCIES[I]##0}"
                CELO_I=`celo64e /DEVICES | grep "$PCIE_A" | grep -oE '^ [0-9]+'`
                CELO_I=${CELO_I## }
                CELO_I=${CELO_I##0}
                advRunLog celo64e /NIC=$CELO_I /EXTLB
                advInfo "Waiting max 10 seconds for single port $ETH back to normal driver ..."
                for ((L=0; L<10; L++)); do
                    [[ -d /sys/class/net/$ETH ]] && break
                    echo -n "."
                    sleep 1
                done
                echo
                if [[ -d /sys/class/net/$ETH ]]; then
                    advInfo "Confirmed single port $ETH normal driver ok"
                else
                    advNotice "There is no single port $ETH"
                fi
            fi

            advInfo "Enabling promisc mode for single port $ETH self loopback ..."
            advRunLog ip link set $ETH down
            advRunLog ip link set $ETH promisc on
            advRunLog ip link set $ETH up
            advInfo "Waiting max 10 seconds for single port $ETH link up ..."
            for ((L=0; L<10; L++)); do
                [[ "1" == "$(cat /sys/class/net/$ETH/carrier)" ]] && break
                echo -n "."
                sleep 1
            done
            echo
            if [[ "1" == "$(cat /sys/class/net/$ETH/carrier)" ]]; then
                advInfo "Confirmed single port $ETH link up"
            else
                advNotice "There is no link up on single port $ETH"
            fi
        fi
        
        advInfo "Setting ${PCIES[I]}($ETH) target: ($SOURCE_MAC $SOURCE_IP) -> ($TARGET_MAC $TARGET_IP) ..."
        pgset $DEVICE "dst_mac $TARGET_MAC"
        pgset $DEVICE "src_mac $SOURCE_MAC"
        pgset $DEVICE "dst_min $TARGET_IP"
        pgset $DEVICE "dst_max $TARGET_IP"
        pgset $DEVICE "src_min $SOURCE_IP"
        pgset $DEVICE "src_max $SOURCE_IP"
    fi
done

advNoTrap

advCleanUp() {
    advNotice "Stopping pktgen ..."
    [[ -n $PKTEGN_START_PROCESS && -d /proc/$PKTEGN_START_PROCESS ]] && kill $PKTEGN_START_PROCESS
    pgset $PKTGEN_PATH/pgctrl "stop" 
    
    advUpdateCounter
    advRestoreMAC
}


showResult() {
    for (( I=0; I<${#ETHS[@]}; I++ )); do
        advNotice "######## Result of ${ETHS[I]} ########"
if [[ -n $VERBOSE_MODE ]]; then
        cat $PKTGEN_PATH/${ETHS[I]}@* | tee -a $ADV_LOG_FILE
else
        tail -n 2 $PKTGEN_PATH/${ETHS[I]}@* | tee -a $ADV_LOG_FILE
fi
        PKTGEN_SPEED=`grep -n1 "Result: " $PKTGEN_PATH/${ETHS[I]}@* | grep -oE "[0-9]+Mb/sec" | grep -oE "[0-9]+"`
        PKTGEN_SPEEDS=(${PKTGEN_SPEEDS[@]} $PKTGEN_SPEED)
        echo
    done
}

compareResult() {
    local Port_Snt_Pkt
    local Port_Snt_Pkt_cmp
    local Port_Rcv_Pkt
    local Port_Snt_Err
    local Port_Rcv_Err

    num_rows=${#ETHS[@]}

    MAX_COLN=2
    MAX_CBUS=4
    MAX_CNIC=4
    MAX_CTXP=6
    MAX_CTXE=6
    MAX_CRXP=6
    MAX_CRXE=6
    MAX_CRXC=6
    MAX_CSNS=6
    MAX_CLNS=6
    
    for ((i=0;i<num_rows;i++)) do
        
        [[ ${#PCIES[$i]} -gt $MAX_CBUS ]] && MAX_CBUS=${#PCIES[i]}
        [[ ${#ETHS[$i]} -gt $MAX_CNIC ]] && MAX_CNIC=${#ETHS[$i]}
        matrix_result[$i,0]=`expr ${matrix_pkts[$i,0]} - ${matrix_ini_pkts[$i,0]}`
        [[ ${#matrix_result[$i,0]} -gt $MAX_CTXP ]] && MAX_CTXP=${#matrix_result[$i,0]}
        matrix_result[$i,1]=`expr ${matrix_pkts[$i,1]} - ${matrix_ini_pkts[$i,1]}`
        [[ ${#matrix_result[$i,1]} -gt $MAX_CTXE ]] && MAX_CTXE=${#matrix_result[$i,1]}
        matrix_result[$i,2]=`expr ${matrix_pkts[$i,2]} - ${matrix_ini_pkts[$i,2]}`
        [[ ${#matrix_result[$i,2]} -gt $MAX_CRXP ]] && MAX_CRXP=${#matrix_result[$i,2]}
        matrix_result[$i,3]=`expr ${matrix_pkts[$i,3]} - ${matrix_ini_pkts[$i,3]}`
        [[ ${#matrix_result[$i,3]} -gt $MAX_CRXE ]] && MAX_CRXE=${#matrix_result[$i,3]}
        matrix_result[$i,4]=`expr ${matrix_pkts[$i,4]} - ${matrix_ini_pkts[$i,4]}`
        [[ ${#matrix_result[$i,4]} -gt $MAX_CRXC ]] && MAX_CRXC=${#matrix_result[$i,4]}
        [[ ${#PKTGEN_SPEEDS[$i]} -gt $MAX_CSNS ]] && MAX_CSNS=${#PKTGEN_SPEEDS[i]}
        [[ ${#LINK_SPEEDS[$i]} -gt $MAX_CLNS ]] && MAX_CLNS=${#LINK_SPEEDS[i]}
    done

    MAX_CBUS=$(($MAX_CBUS + 1))
    MAX_CNIC=$(($MAX_CNIC + 1))
    MAX_CTXP=$(($MAX_CTXP + 1))
    MAX_CTXE=$(($MAX_CTXE + 1))
    MAX_CRXP=$(($MAX_CRXP + 1))
    MAX_CRXE=$(($MAX_CRXE + 1))
    MAX_CRXC=$(($MAX_CRXC + 1))
    MAX_CSNS=$(($MAX_CSNS + 1))
    MAX_CLNS=$(($MAX_CLNS + 1))

    [[ -n $1 ]] && advInfo "Proceeding:" || advInfo "Result:"
    LINE=`printf "% ${MAX_COLN}s % ${MAX_CBUS}s % ${MAX_CNIC}s % ${MAX_CTXP}s % ${MAX_CTXE}s % ${MAX_CRXP}s % ${MAX_CRXE}s % ${MAX_CRXC}s % ${MAX_CSNS}s % ${MAX_CLNS}s" \
        "NO" PCI NIC TXPKTs TXErrs RXPKTs RXErrs RXCRCs SntSpd LnkSpd`
    echo "$LINE" | tee -a $ADV_LOG_FILE
    for ((i=0;i<num_rows;i++)) do
        [[ -n $1 ]] && PKTGEN_SPEED=0 || PKTGEN_SPEED=${PKTGEN_SPEEDS[i]}
        LINE=`printf "%0${MAX_COLN}d % ${MAX_CBUS}s % ${MAX_CNIC}s % ${MAX_CTXP}d % ${MAX_CTXE}d % ${MAX_CRXP}d % ${MAX_CRXE}d % ${MAX_CRXC}d % ${MAX_CSNS}d % ${MAX_CLNS}d" \
        $((i + 1)) ${PCIES[$i]} ${ETHS[$i]} ${matrix_result[$i,0]} ${matrix_result[$i,1]} ${matrix_result[$i,2]} ${matrix_result[$i,3]} ${matrix_result[$i,4]} $PKTGEN_SPEED ${LINK_SPEEDS[i]}`
        echo "$LINE" | tee -a $ADV_LOG_FILE
    done
    
    [[ -n $1 ]] && return 0

    [[ -n $VERBOSE_MODE ]] && advInfo "Packet loss tolerance: ${THIS_PKT_LOST_PER}%"

    for ((i=0;i<num_rows;i++)) do
        ## Port 
        ETH=${ETHS[i]}
        eval IS_SLP=\$SLP_$ETH
        let r=i%2
        if [[ $r -eq 0 && ($TEST_MODE == "loop" || $TEST_MODE == "original") && $IS_SLP -ne 1 ]]; then
            let j=i+1
            Port1_Snt_Pkt=`expr ${matrix_pkts[$i,0]} - ${matrix_ini_pkts[$i,0]}`
            Port1_Rcv_Pkt=`expr ${matrix_pkts[$i,2]} - ${matrix_ini_pkts[$i,2]}`
            Port1_Snt_Err=`expr ${matrix_pkts[$i,1]} - ${matrix_ini_pkts[$i,1]}`
            Port1_Rcv_Err=`expr ${matrix_pkts[$i,3]} - ${matrix_ini_pkts[$i,3]}`
            Port1_Crc_Err=`expr ${matrix_pkts[$i,4]} - ${matrix_ini_pkts[$i,4]}`
            Port1_Err=$(($Port1_Snt_Err + $Port1_Rcv_Err + $Port1_Crc_Err))
            if [[ $j -lt $num_rows ]]; then
                Port2_Snt_Pkt=`expr ${matrix_pkts[$j,0]} - ${matrix_ini_pkts[$j,0]}`
                Port2_Rcv_Pkt=`expr ${matrix_pkts[$j,2]} - ${matrix_ini_pkts[$j,2]}`
                Port2_Snt_Err=`expr ${matrix_pkts[$j,1]} - ${matrix_ini_pkts[$j,1]}`
                Port2_Rcv_Err=`expr ${matrix_pkts[$j,3]} - ${matrix_ini_pkts[$j,3]}`
                Port2_Crc_Err=`expr ${matrix_pkts[$j,4]} - ${matrix_ini_pkts[$j,4]}`
                Port2_Err=$(($Port2_Snt_Err + $Port2_Rcv_Err + $Port2_Crc_Err))
                
                ## Compare port1 sent <> port2 recv
                unset PASS1_2
                DIFF=$(($Port1_Snt_Pkt - $Port2_Rcv_Pkt))
                [[ $DIFF -eq 0 ]] && EQ="==" || EQ="<>"
                TORR=$(($Port1_Snt_Pkt * $THIS_PKT_LOST_PER / 100))
                [[ $Port1_Snt_Pkt -eq 0 ]] && LOSS=0 || LOSS=$(($DIFF * 100 / $Port1_Snt_Pkt))
                [[ ${LINK_SPEEDS[i]} -eq 0 ]] && THROUGHPUT=0 || THROUGHPUT=$((${PKTGEN_SPEEDS[i]}*100/${LINK_SPEEDS[i]}))
                advInfo "${ETHS[$j]} -> ${ETHS[$i]}: sent $Port1_Snt_Pkt $EQ recv $Port2_Rcv_Pkt, loss $DIFF($LOSS%), throughput $THROUGHPUT%"
                
                if [[ $Port1_Snt_Pkt -eq 0 || $Port2_Rcv_Pkt -eq 0 ]]; then
                    advError "\t${ETHS[$i]} -> ${ETHS[$j]}: sent $Port1_Snt_Pkt, recv $Port2_Rcv_Pkt"
                else
                    if [[ $DIFF -eq 0 ]]; then
                        advInfo "\t${ETHS[$i]} -> ${ETHS[$j]}: sent $Port1_Snt_Pkt == recv $Port2_Rcv_Pkt"
                        PASS1_2=1
                    else
                        advNotice "\t${ETHS[$i]} -> ${ETHS[$j]}: sent $Port1_Snt_Pkt <> recv $Port2_Rcv_Pkt"
                        
                        if [[ $DIFF -lt $TORR ]]; then
                            advInfo "\t${ETHS[$i]} -> ${ETHS[$j]}: loss $DIFF(${LOSS}%) < $TORR(${THIS_PKT_LOST_PER}%)"
                            PASS1_2=1
                        else
                            advError "\t${ETHS[$i]} -> ${ETHS[$j]}: loss $DIFF(${LOSS}%) > $TORR(${THIS_PKT_LOST_PER}%)"
                        fi
                    fi
                    
                    if [[ $Port1_Err -gt 0 ]]; then
                        if [[ -n $THIS_NO_ERR_ALLOWED ]]; then
                            advError "\t${ETHS[$i]} -> ${ETHS[$j]}: got $Port1_Err errors"
                            unset PASS1_2
                        elif [[ -n $THIS_ERR_ALLOWED ]]; then
                            echo THIS_ERR_ALLOWED=$THIS_ERR_ALLOWED
                            if [[ $Port1_Err -gt $THIS_ERR_ALLOWED ]]; then
                                advError "\t${ETHS[$i]} -> ${ETHS[$j]}: got $Port1_Err errors > $THIS_ERR_ALLOWED"
                                unset PASS1_2
                            else
                                advNotice "\t${ETHS[$i]} -> ${ETHS[$j]}: allow with $Port1_Err errors <= $THIS_ERR_ALLOWED"
                            fi
                        elif [[ -n $THIS_ERR_ALLOWED_PCT ]]; then
                            ERR_ALLOWED=$(($THIS_ERR_ALLOWED_PCT * $Port1_Snt_Pkt / 100))
                            if [[ $Port1_Err -gt $ERR_ALLOWED ]]; then
                                advError "\t${ETHS[$i]} -> ${ETHS[$j]}: got $Port1_Err errors > $ERR_ALLOWED(${THIS_ERR_ALLOWED_PCT}%)"
                                unset PASS1_2
                            else
                                advNotice "\t${ETHS[$i]} -> ${ETHS[$j]}: allow with $Port1_Err errors <= $ERR_ALLOWED(${THIS_ERR_ALLOWED_PCT}%)"
                            fi
                        else
                            advNotice "\t${ETHS[$i]} -> ${ETHS[$j]}: allow with $Port1_Err errors"
                        fi
                    else
                        advInfo "\t${ETHS[$i]} -> ${ETHS[$j]}: no error"
                    fi
                    
                    advInfo "\t${ETHS[$i]} -> ${ETHS[$j]}: thourghput ${PKTGEN_SPEEDS[i]}/${LINK_SPEEDS[i]}=$THROUGHPUT%"
                    if [[ -n $THIS_CHECK_THROUGHPUT ]]; then
                        if [[ $THROUGHPUT -gt $THIS_CHECK_THROUGHPUT ]]; then
                            advInfo "\t${ETHS[$i]} -> ${ETHS[$j]}: thourghput% $THROUGHPUT% > required $THIS_CHECK_THROUGHPUT%"
                        else
                            advError "\t${ETHS[$i]} -> ${ETHS[$j]}: thourghput% $THROUGHPUT% <= required $THIS_CHECK_THROUGHPUT%"
                            unset PASS1_2
                        fi                        
                    fi
                fi
                
                ## Compare port2 sent <> port1 recv
                unset PASS2_1
                DIFF=$(($Port2_Snt_Pkt - $Port1_Rcv_Pkt))
                [[ $DIFF -eq 0 ]] && EQ="==" || EQ="<>"
                TORR=$(($Port2_Snt_Pkt * $THIS_PKT_LOST_PER / 100))
                [[ $Port2_Snt_Pkt -eq 0 ]] && LOSS=0 || LOSS=$(($DIFF * 100 / $Port2_Snt_Pkt))
                [[ ${LINK_SPEEDS[j]} -eq 0 ]] && THROUGHPUT=0 || THROUGHPUT=$((${PKTGEN_SPEEDS[j]}*100/${LINK_SPEEDS[j]}))
                advInfo "${ETHS[$i]} -> ${ETHS[$j]}: sent $Port2_Snt_Pkt $EQ recv $Port1_Rcv_Pkt, loss $DIFF($LOSS%), throughput $THROUGHPUT%"
                
                if [[ $Port2_Snt_Pkt -eq 0 || $Port1_Rcv_Pkt -eq 0 ]]; then
                    advError "\t${ETHS[$j]} -> ${ETHS[$i]}: sent $Port2_Snt_Pkt, recv $Port1_Rcv_Pkt"
                else
                    if [[ $DIFF -eq 0 ]]; then
                        advInfo "\t${ETHS[$j]} -> ${ETHS[$i]}: sent $Port2_Snt_Pkt == recv $Port1_Rcv_Pkt"
                        PASS2_1=1
                    else
                        advNotice "\t${ETHS[$j]} -> ${ETHS[$i]}: sent $Port2_Snt_Pkt <> recv $Port1_Rcv_Pkt"
                        
                        if [[ $DIFF -lt $TORR ]]; then
                            advInfo "\t${ETHS[$j]} -> ${ETHS[$i]}: loss $DIFF(${LOSS}%) < $TORR(${THIS_PKT_LOST_PER}%)"
                            PASS2_1=1
                        else
                            advError "\t${ETHS[$j]} -> ${ETHS[$i]}: loss $DIFF(${LOSS}%) > $TORR(${THIS_PKT_LOST_PER}%)"
                        fi
                    fi
                    
                    if [[ $Port2_Err -gt 0 ]]; then
                        if [[ -n $THIS_NO_ERR_ALLOWED ]]; then
                            advError "\t${ETHS[$j]} -> ${ETHS[$i]}: got $Port2_Err errors"
                            unset PASS2_1
                        elif [[ -n $THIS_ERR_ALLOWED ]]; then
                            if [[ $Port2_Err -gt $THIS_ERR_ALLOWED ]]; then
                                advError "\t${ETHS[$j]} -> ${ETHS[$i]}: got $Port2_Err errors > $THIS_ERR_ALLOWED"
                                unset PASS2_1
                            else
                                advNotice "\t${ETHS[$j]} -> ${ETHS[$i]}: allow with $Port2_Err errors <= $THIS_ERR_ALLOWED"
                            fi
                        elif [[ -n $THIS_ERR_ALLOWED_PCT ]]; then
                            ERR_ALLOWED=$(($THIS_ERR_ALLOWED_PCT * $Port2_Snt_Pkt / 100))
                            if [[ $Port2_Err -gt $ERR_ALLOWED ]]; then
                                advError "\t${ETHS[$j]} -> ${ETHS[$i]}: got $Port2_Err errors > $ERR_ALLOWED(${THIS_ERR_ALLOWED_PCT}%)"
                                unset PASS2_1
                            else
                                advNotice "\t${ETHS[$j]} -> ${ETHS[$i]}: allow with $Port2_Err errors <= $ERR_ALLOWED(${THIS_ERR_ALLOWED_PCT}%)"
                            fi
                        else
                            advNotice "\t${ETHS[$j]} -> ${ETHS[$i]}: allow with $Port2_Err errors"
                        fi
                    else
                        advInfo "\t${ETHS[$j]} -> ${ETHS[$i]}: no error"
                    fi
                    
                    advInfo "\t${ETHS[$j]} -> ${ETHS[$i]}: thourghput ${PKTGEN_SPEEDS[j]}/${LINK_SPEEDS[j]}=$THROUGHPUT%"
                    if [[ -n $THIS_CHECK_THROUGHPUT ]]; then
                        if [[ $THROUGHPUT -gt $THIS_CHECK_THROUGHPUT ]]; then
                            advInfo "\t${ETHS[$j]} -> ${ETHS[$i]}: thourghput% $THROUGHPUT% > required $THIS_CHECK_THROUGHPUT%"
                        else
                            advError "\t${ETHS[$j]} -> ${ETHS[$i]}: thourghput% $THROUGHPUT% <= required $THIS_CHECK_THROUGHPUT%"
                            unset PASS2_1
                        fi                        
                    fi
                fi
                
                if [[ -n $PASS1_2 && -n $PASS2_1 ]]; then
                    PASSED_ITEMS=(${PASSED_ITEMS[@]} "${ETHS[$i]}<->${ETHS[$j]}")
                else
                    FAILED_ITEMS=(${FAILED_ITEMS[@]} "${ETHS[$i]}<->${ETHS[$j]}")
                fi
                
                let i=i+1
                continue
            fi
        elif [[ $IS_SLP -eq 1 ]]; then
            ## Compare port self sent <> recv
            Port1_Snt_Pkt=`expr ${matrix_pkts[$i,0]} - ${matrix_ini_pkts[$i,0]}`
            Port1_Rcv_Pkt=`expr ${matrix_pkts[$i,2]} - ${matrix_ini_pkts[$i,2]}`
            Port1_Snt_Err=`expr ${matrix_pkts[$i,1]} - ${matrix_ini_pkts[$i,1]}`
            Port1_Rcv_Err=`expr ${matrix_pkts[$i,3]} - ${matrix_ini_pkts[$i,3]}`
            Port1_Crc_Err=`expr ${matrix_pkts[$i,4]} - ${matrix_ini_pkts[$i,4]}`
            Port1_Err=$(($Port1_Snt_Err + $Port1_Rcv_Err + $Port1_Crc_Err))
            
            unset PASS_SLP
            DIFF=$(($Port1_Snt_Pkt - $Port1_Rcv_Pkt))
            [[ $DIFF -eq 0 ]] && EQ="==" || EQ="<>"
            TORR=$(($Port1_Snt_Pkt * $THIS_PKT_LOST_PER / 100))
            [[ $Port1_Snt_Pkt -eq 0 ]] && LOSS=0 || LOSS=$(($DIFF * 100 / $Port1_Snt_Pkt))
            [[ -z ${LINK_SPEEDS[i]} ]] && THROUGHPUT=0 || THROUGHPUT=$((${PKTGEN_SPEEDS[i]}*100/${LINK_SPEEDS[i]}))
            advInfo "${ETHS[$i]}(tx -> rx): sent $Port1_Snt_Pkt $EQ recv $Port1_Rcv_Pkt, loss $DIFF($LOSS%), throughput $THROUGHPUT%"
            
            if [[ $Port1_Snt_Pkt -eq 0 || $Port1_Rcv_Pkt -eq 0 ]]; then
                advError "\t${ETHS[$i]}(tx -> rx): sent $Port1_Snt_Pkt, recv $Port1_Rcv_Pkt"
            else
                if [[ $DIFF -eq 0 ]]; then
                    advPassed "\t${ETHS[$i]}(tx -> rx): sent $Port1_Snt_Pkt == recv $Port1_Rcv_Pkt"
                    PASS_SLP=1
                else
                    advNotice "\t${ETHS[$i]}(tx -> rx): sent $Port1_Snt_Pkt <> recv $Port1_Rcv_Pkt"
                    
                    if [[ $DIFF -lt $TORR ]]; then
                        advPassed "\t${ETHS[$i]}(tx -> rx): loss $DIFF(${LOSS}%) < $TORR(${THIS_PKT_LOST_PER}%)"
                        PASS_SLP=1
                    else
                        advError "\t${ETHS[$i]}(tx -> rx): loss $DIFF(${LOSS}%) > $TORR(${THIS_PKT_LOST_PER}%)"
                    fi
                fi
                
                if [[ $Port1_Err -gt 0 ]]; then
                    if [[ -n $THIS_NO_ERR_ALLOWED ]]; then
                        advError "\t${ETHS[$i]}(tx -> rx): got $Port1_Err errors"
                        unset PASS_SLP
                    elif [[ -n $THIS_ERR_ALLOWED ]]; then
                        if [[ $Port1_Err -gt $THIS_ERR_ALLOWED ]]; then
                            advError "\t${ETHS[$i]}(tx -> rx): got $Port1_Err errors > $THIS_ERR_ALLOWED"
                            unset PASS_SLP
                        else
                            advNotice "\t${ETHS[$i]}(tx -> rx): allow with $Port1_Err errors <= $THIS_ERR_ALLOWED"
                        fi
                    elif [[ -n $THIS_ERR_ALLOWED_PCT ]]; then
                        ERR_ALLOWED=$(($THIS_ERR_ALLOWED_PCT * $Port1_Snt_Pkt / 100))
                        if [[ $Port1_Err -gt $ERR_ALLOWED ]]; then
                            advError "\t${ETHS[$i]}(tx -> rx): got $Port1_Err errors > $ERR_ALLOWED(${THIS_ERR_ALLOWED_PCT}%)"
                            unset PASS_SLP
                        else
                            advNotice "\t${ETHS[$i]}(tx -> rx): allow with $Port1_Err errors <= $ERR_ALLOWED(${THIS_ERR_ALLOWED_PCT}%)"
                        fi
                    else
                        advNotice "\t${ETHS[$i]}(tx -> rx): allow with $Port1_Err errors"
                    fi
                else
                    advPassed "\t${ETHS[$i]}(tx -> rx): no error"
                fi
                
                advInfo "\t${ETHS[$i]}(tx -> rx): thourghput ${PKTGEN_SPEEDS[i]}/${LINK_SPEEDS[i]}=$THROUGHPUT%"
                if [[ -n $THIS_CHECK_THROUGHPUT ]]; then
                    if [[ $THROUGHPUT -gt $THIS_CHECK_THROUGHPUT ]]; then
                        advPassed "\t${ETHS[$i]}(tx -> rx): thourghput% $THROUGHPUT% > required $THIS_CHECK_THROUGHPUT%"
                    else
                        advError "\t${ETHS[$i]}(tx -> rx): thourghput% $THROUGHPUT% <= required $THIS_CHECK_THROUGHPUT%"
                        unset PASS_SLP
                    fi                        
                fi
            fi
            
            if [[ -n $PASS_SLP ]]; then
                PASSED_ITEMS=(${PASSED_ITEMS[@]} "${ETHS[$i]}-tx->rx")
            else
                FAILED_ITEMS=(${FAILED_ITEMS[@]} "${ETHS[$i]}-tx->rx")
            fi
            
            continue
        elif [[ $TEST_MODE != "loop" ]]; then
            # Single port result
            Port_Snt_Pkt=`expr ${matrix_pkts[$i,0]} - ${matrix_ini_pkts[$i,0]}`
            Port_Rcv_Pkt=`expr ${matrix_pkts[$i,2]} - ${matrix_ini_pkts[$i,2]}`
            Port_Snt_Err=`expr ${matrix_pkts[$i,1]} - ${matrix_ini_pkts[$i,1]}`
            Port_Rcv_Err=`expr ${matrix_pkts[$i,3]} - ${matrix_ini_pkts[$i,3]}`
            Port_Crc_Err=`expr ${matrix_pkts[$i,4]} - ${matrix_ini_pkts[$i,4]}`

            advNotice "${ETHS[$i]}: sent $Port_Snt_Pkt (err $Port_Snt_Err), recv $Port_Rcv_Pkt (err $Port_Rcv_Err, crc $Port_Crc_Err)"
        fi
    done
    [[ -n $PASSED_ITEMS ]] && advInfo "[PASSED ITEMS] [$ADV_TEST_ITEM] [${PASSED_ITEMS[@]}]"
    [[ -z $FAILED_ITEMS ]] && advPassed "[$ADV_TEST_ITEM]" && return 0
    
    advNotice "[FAILED ITEMS] [$ADV_TEST_ITEM] [${FAILED_ITEMS[@]}]"
    advFailed "[$ADV_TEST_ITEM]"
    return 1
}

advTrap "advCleanUp; showResult; compareResult; exit 1"

advNotice "Starting pktgen, Ctrl+C to terminate ..."
START_TIME=`date +%s`
pgset $PKTGEN_PATH/pgctrl "start" &
PKTEGN_START_PROCESS=$!

REFRESH_COUNT=0
PROCESS_CHAR=('-' '\\' '|' '/')
P=0
while true; do
    sleep 1
    
    if [[ $THIS_REFRESH -gt 0 ]]; then
        let REFRESH_COUNT=REFRESH_COUNT+1
        if [[ $THIS_REFRESH -eq $REFRESH_COUNT ]]; then
            REFRESH_COUNT=0
            echo
            advUpdateCounter
            compareResult 1
        fi
#    else
#        echo -ne "${PROCESS_CHAR[P]}"\\r
#        let P=P+1
#        [[ $P -ge ${#PROCESS_CHAR[@]} ]] && P=0
    fi
    
    if [[ -n $THIS_TIME_TO_RUN ]]; then
        CURRENT_TIME=`date +%s`
        DIFF=$(($CURRENT_TIME - $START_TIME))
        if [[ $DIFF -ge $THIS_TIME_TO_RUN ]]; then
            echo
            advNotice "Run in ${DIFF}s, time reach ${THIS_TIME_TO_RUN}s, stopping ..."
            advCleanUp
        fi
    fi
    for (( I=0; I<${#DEVICES[@]}; I++ )); do
        DEVICE=$PKTGEN_PATH/kpktgend_${DEVICES[I]}
        grep -qE "^Running: [a-z0-9\.\-\_]+" $DEVICE
        if [[ $? -ne 0 ]]; then
            echo
            ETH=`grep -oE "^Stopped: [a-z0-9\.\-\_]+" $DEVICE | awk '{print $2}'`
            advNotice "pktgen on $ETH stopped"
            DEVICES=(${DEVICES[@]:0:$I} ${DEVICES[@]:$(($I + 1))})
            let I=I-1
        fi
        #grep "^Running: [a-z0-9\.\-\_]" $DEVICE
    done
    
    if [[ -z $DEVICES ]]; then
        advNotice "All devices stopped"
        break
    fi
done
echo

sleep 3
advNoTrap
advUpdateCounter
advRestoreMAC
showResult
compareResult
tmp_result=$?
[[ -n $VERBOSE_MODE ]] && echo " LOG_FILE : $ADV_LOG_FILE "
#[[ -n $VERBOSE_MODE ]] && cat $ADV_LOG_FILE

[[ $tmp_result == 0 ]] && exit 0 || exit 1
