#!/bin/bash
# ------------------------------------------------------------------------------
# Copyright (c) 2016-2023 Advantech Co. Ltd.
# All Rights Reserved
#
# Run disk read-write testing
# ------------------------------------------------------------------------------

# Script-version-start ---------------------------------------------------------
# !!! This section is generated by standardize.sh, never add content here manually!
ADV_SCRIPT_REVISION="g51"
ADV_SCRIPT_MD5="a98e85504958871e91ec8f5c588fb118"
ADV_SCRIPT_DATE="2025-02-18 02:49:45"
advShowHelp() {
     echo -e "\e[07m"$(basename "$0")" $ADV_SCRIPT_REVISION ($ADV_SCRIPT_DATE)\e[0m"
     echo -e "$ADV_SCRIPT_HELP"
     [ -z $1 ] && exit 0 || exit $1 
}
# !!! This section is generated by standardize.sh, never add content here manually!
# Script-version-end -----------------------------------------------------------

# Basic-functions-start --------------------------------------------------------
# !!! This section is generated by standardize.sh, never add content here manually!
export ADV_SYS_DATE="date +%Y.%m.%d"
export ADV_SYS_TIME="date +%Y.%m.%d-%H.%M.%S"
export ADV_SYS_TIME_STRING="eval date '+%Y.%m.%d %H:%M:%S'"
[[ -z $ADV_TEST_ITEM ]] && ADV_TEST_ITEM="$(basename "$0")"

advGetCurrentPath() {
    local SOURCE="${BASH_SOURCE[0]}"
    while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
        local DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
        SOURCE="$(readlink "$SOURCE")"
        # if $SOURCE was a relative symlink, we need to resolve it relative 
        # to the path where the symlink file was located
        [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" 
    done
    echo $( cd -P "$( dirname "$SOURCE" )" && pwd )
    return 0
}

advToUpper() {
    [[ -z $1 ]] && read INPUT || INPUT="$@"
    echo "$INPUT" | tr [:lower:] [:upper:]
    return 0
}

advToLower() {
    [[ -z $1 ]] && read INPUT || INPUT="$@"
    echo "$INPUT" | tr [:upper:] [:lower:]
    return 0
}

advError() {
    local CONTENT="["`$ADV_SYS_TIME_STRING`"] [ERROR] $@"
    [[ -n $ADV_LOG_TO_PXE_SERVER ]] && logger -t "adv_diag_log" -p user.error "${ADV_LOG_FILE#*/adv_diag_log/} $CONTENT"
    echo -e "\033[31m""$CONTENT""\033[0m" >&2
    [[ -e $ADV_LOG_FILE ]] && echo -e "$CONTENT" >> $ADV_LOG_FILE
    return 0
}

advNotice() {
    local CONTENT="["`$ADV_SYS_TIME_STRING`"] [NOTICE] $@"
    [[ -n $ADV_LOG_TO_PXE_SERVER ]] && logger -t "adv_diag_log" -p user.notice "${ADV_LOG_FILE#*/adv_diag_log/} $CONTENT"
    echo -e "\033[33m""$CONTENT""\033[0m"
    [[ -e $ADV_LOG_FILE ]] && echo -e "$CONTENT" >> $ADV_LOG_FILE
    return 0
}

advInfo() {
    local CONTENT="["`$ADV_SYS_TIME_STRING`"] [INFO] $@"
    [[ -n $ADV_LOG_TO_PXE_SERVER ]] && logger -t "adv_diag_log" -p user.info "${ADV_LOG_FILE#*/adv_diag_log/} $CONTENT"
    echo -e "$CONTENT"
    [[ -e $ADV_LOG_FILE ]] && echo -e "$CONTENT" >> $ADV_LOG_FILE
    return 0
}

advInfof () {
    local FORMAT="%s %s %s $1"
    shift

    printf "${FORMAT}" "["$($ADV_SYS_TIME_STRING)"]" "[INFO]" "$@"

    local CONTENT=$(printf "${FORMAT}" "["$($ADV_SYS_TIME_STRING)"]" "[INFO]" "$@" | sed "s/\x1B\[[0-9;]*[mK]//g")
    [[ -n $ADV_LOG_TO_PXE_SERVER ]] && logger -t "adv_diag_log" -p user.info "${ADV_LOG_FILE#*/adv_diag_log/} $CONTENT"
    [[ -e $ADV_LOG_FILE ]] && echo -e "$CONTENT" >> $ADV_LOG_FILE

    return 0
}

advFailed() {
    local CONTENT="["`$ADV_SYS_TIME_STRING`"] [FAIL] $@"
    [[ -n $ADV_LOG_TO_PXE_SERVER ]] && logger -t "adv_diag_log" -p user.error "${ADV_LOG_FILE#*/adv_diag_log/} $CONTENT"
    echo -e "\033[31m""$CONTENT""\033[0m" >&2
    [[ -e $ADV_LOG_FILE ]] && echo -e "$CONTENT" >> $ADV_LOG_FILE
    return 0
}

advPassed() {
    local CONTENT="["`$ADV_SYS_TIME_STRING`"] [PASS] $@"
    [[ -n $ADV_LOG_TO_PXE_SERVER ]] && logger -t "adv_diag_log" -p user.notice "${ADV_LOG_FILE#*/adv_diag_log/} $CONTENT"
    echo -e "\033[32m""$CONTENT""\033[0m" >&2
    [[ -e $ADV_LOG_FILE ]] && echo -e "$CONTENT" >> $ADV_LOG_FILE
    return 0
}

advRunLog() {
    advInfo "Running: $@"
    "$@" 2>&1 | tee -a "$ADV_LOG_FILE"
    return ${PIPESTATUS[0]}
}

advCheckParam() {
    local TYPE="$1"
    local NAME="$2"
    shift 2

    [[ $TYPE = "unknown" ]] && advError "Unknown parameter: $NAME" && exit 1
    
    local VALUE="$@"
    [[ -z $VALUE ]] && advError "Missing $NAME" && exit 1

    case $TYPE in
        "any")
            PATTERN='.*'
            ;;
        "digit")
            PATTERN='^[0-9]$'
            ;;
        "number")
            PATTERN='^[0-9]+$'
            ;;
        "nlist")
            PATTERN='^[0-9,\-]+$'
            ;;
        nrange-*)
            PATTERN='^[0-9]+$'
            ;;
        "hex")
            PATTERN='^[0-9A-Fa-f]+$'
            ;;
        "float")
            PATTERN='^([0-9]+\.[0-9]+|[0-9]+)$'
            ;;
        "pcie")
            PATTERN='^[0-9A-Fa-f]+:[0-9A-Fa-f]+\.[0-9A-Fa-f]$'
            ;;
        "ip")
            PATTERN='^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$'
            ;;
        *)
            PATTERN="$TYPE"
            ;;
    esac
    if [[ ! "$VALUE" =~ $PATTERN ]]; then
        advError "Invalid $NAME: $VALUE"
        exit 1
    fi
    if [[ "$TYPE" =~ ^nrange-.* ]]; then
        local RANGE_S=`echo "$TYPE" | cut -d '-' -f 2`
        local RANGE_E=`echo "$TYPE" | cut -d '-' -f 3`
        [[ $VALUE -lt $RANGE_S || $VALUE -gt $RANGE_E ]] && advError "Invalid $NAME ($RANGE_S-$RANGE_E): $VALUE" && exit 1
    fi
}

advGetNetPCIEs() {
    local NET_PCIES="`ls -l /sys/class/net/ | grep -oE '/[0-9A-Fa-f:.]+/net' | cut -d '/' -f 2 | sort`"
    [[ -z $1 ]] && echo "$NET_PCIES" && return 0
    echo "$NET_PCIES" | grep "$1:"
    return $?
}

advTrap() {
    local CALLBACK="$1"; shift
    [[ $# -eq 0 ]] && ADV_SIGS=(SIGINT SIGTERM SIGHUP) || ADV_SIGS=($@)
    for sig in ${ADV_SIGS[@]}; do
        trap "advTrapCallback $sig $CALLBACK" "$sig"
    done
}

advNoTrap() {
    [[ $# -ne 0 ]] && ADV_SIGS=($@)
    [[ -z $ADV_SIGS ]] && ADV_SIGS=(SIGINT SIGTERM SIGHUP)
    trap - ${ADV_SIGS[@]}
    unset ADV_SIGS
}

advTrapCallback() {
    advNotice "Cancelling by $1 ..."
    shift
    $@
}
# !!! This section is generated by standardize.sh, never add content here manually!
# Basic-functions-end ----------------------------------------------------------

# Log-functions-start ----------------------------------------------------------
# !!! This section is generated by standardize.sh, never add content here manually!
ADV_TIME_TAG=`$ADV_SYS_TIME`
ADV_SCRIPT_PATH=`advGetCurrentPath`
# If log path is set, use it, otherwise create one
if [[ -z $ADV_OUTPUT_PATH ]]; then
    ADV_OUTPUT_PATH="$HOME/adv_diag_log"
    mkdir -p $ADV_OUTPUT_PATH
    export ADV_OUTPUT_PATH
fi
# If log file is set, use it, otherwise create one
if [[ -z $ADV_LOG_FILE ]]; then
    ADV_LOG_FILE="$ADV_OUTPUT_PATH/`basename "$0"`-$ADV_TIME_TAG.log"
    touch $ADV_LOG_FILE
    export ADV_LOG_FILE
fi
# If adv.pxe.diaglog is set in /proc/cmdline, enable logger
grep -q 'adv.pxe.diaglog' /proc/cmdline
if [[ $? -eq 0 ]]; then
    PXE_SERVER=`grep -oE 'adv\.pxe\.server=[^ ]+' /proc/cmdline | awk -F'=' '{print $2}'`
    [[ -n $PXE_SERVER ]] && export ADV_LOG_TO_PXE_SERVER=$PXE_SERVER
fi
# Log script version
advInfo "$(basename "$0") $ADV_SCRIPT_REVISION ($ADV_SCRIPT_DATE)"
# !!! This section is generated by standardize.sh, never add content here manually!
# Log-functions-end ------------------------------------------------------------

# SymbolLinkCall-functions-start -----------------------------------------------
# !!! This section is generated by standardize.sh, never add content here manually!
ADV_SLN_CALL_NAME=$(basename "$0")
ADV_SCRIPT_ME="$(basename "$(test -L "$0" && readlink "$0" || echo "$0")")"
ADV_SCRIPT_ME=${ADV_SCRIPT_ME%.sh}
if [[ "$ADV_SLN_CALL_NAME" =~ .*_$ADV_SCRIPT_ME\.sh_.* ]]; then
    export PATH=$PATH:$ADV_SCRIPT_PATH
    advInfo "Calling from symbol link $ADV_SLN_CALL_NAME ..."
    PARAMS=${ADV_SLN_CALL_NAME#*$ADV_SCRIPT_ME.sh_}
    PARAMS=${PARAMS//__/+}
    PARAMS=${PARAMS//_/ }
    PARAMS=${PARAMS//+/_}
    advNotice "Redirecting to run: $ADV_SCRIPT_ME.sh $PARAMS"
    export ADV_TEST_ITEM=$ADV_SLN_CALL_NAME
    $ADV_SCRIPT_ME.sh $PARAMS
    exit
fi
[[ -z $ADV_TEST_ITEM ]] && ADV_TEST_ITEM="$(basename "$0")"
# !!! This section is generated by standardize.sh, never add content here manually!
# SymbolLinkCall-functions-end ------------------------------------------------------------

ADV_SCRIPT_HELP="Run disk r/w on device sequentially.
It will find a valid and writable partition from device, 
also check free space. If no valid partition, clear current partition
and create a new one (with --mkpart).
The current mounted root fs is not touched except use -a, and never be
re-partition even with --mkpart.
Usage: "$(basename "$0")" [options] disks
Options:
    -a                      not ignore current mounted system root device
    -r                      use random content in file, instead of all 0
    -s <file-size>          size of file, default to 64MB
    -k                      use KB asw file size instead of MB, and it will not run sync
    -f <file-to-duplicate>  times to duplicate single file in a round, default 10
    -d <times-to-read>      times to read while duplicated single file, default 1
    -l <loop-to-test>       round to run test, default 0, means run infinitely
    -i <interval>           interval between each round, in seconds, default 0
    -t <time-to-run>        time to run test, in seconds
                            test is stopped when time reach after a round done 
                            or all rounds finished
    -g <source-path>        source file is generated in this path
                            if source patch not available, try \"/dev/shm\" first, then \"/tmp\"
    --mkpart                create a new partition if file system not exist, 
                            if file system  exist, this option takes no effect,
                            anyway, it will destroy data on disk, be careful
        --force             destroy and make partition without prompt
	-e <filetype>	    format filetype ext2 (2) / ext3 (3) /ext (4) ,default 3
Disks:
    all         all storage devices
    <dev name>  block device name, like sda, sdb1, or lvm volume name
    <pci bus>   single pci bus of sata controller like 00:1f.2
Notes:
    current mounted system root device is ignored even if specified in disks,
    to test on it, use -a
    
    if partition not exist on device, the test will fail, to create 
    partition anyway, use --mkpart
Example:
    "$(basename "$0")" -f 120 sdb 00:1f.2
Disks in current system:
""`ls -l /sys/class/block/ | grep -v -E '(loop)|(ram[0-9]+)|(sr[0-9]+)' | grep -E '/[^/]+$' | awk '{print $9}'`"
[[ -z $1 ]] && advShowHelp
[[ "$1" = "-h" || "$1" = "--help" ]] && advShowHelp

# Parse parameters
unset THIS_ANY_DEVICE
unset THIS_MAKE_PART
unset THIS_RANDOM_FILE
THIS_FILE_SIZE=64
THIS_DUPLICATE=10
THIS_READ=1
THIS_LOOP=0
THIS_INTERVAL=0
THIS_FILETYPE=3
unset THIS_TIME_TO_RUN
unset THIS_FORCE
while [[ $# -gt 0 ]]; do
    case $1 in
        "-a")
            THIS_ANY_DEVICE=1
            ;;
        "-r")
            THIS_RANDOM_FILE=1
            ;;
        "-s")
            advCheckParam number "file size" "$2"
            THIS_FILE_SIZE=$2
            shift
            ;;
        "-k")
            THIS_KB=1
            ;;
        "-f")
            advCheckParam number "file duplication times" "$2"
            THIS_DUPLICATE=$2
            shift
            ;;
        "-d")
            advCheckParam number "file read times" "$2"
            THIS_READ=$2
            shift
            ;;
        "-l")
            advCheckParam number "loops to test" "$2"
            THIS_LOOP=$2
            shift
            ;;
        "-i")
            advCheckParam number "interval" "$2"
            THIS_INTERVAL=$2
            shift
            ;;
        "-t")
            advCheckParam number "seconds to run" "$2"
            THIS_TIME_TO_RUN=$2
            shift
            ;;
        "-e")
            advCheckParam number "ext2/3/4" "$2"
            THIS_FILETYPE=$2
            shift
            ;;
        "-g")
            advCheckParam any "source path" "$2"
            THIS_SOURCE_PATH="$2"
            shift
            ;;
        "--mkpart")
            THIS_MAKE_PART=1
            ;;
        "--force")
            THIS_FORCE=1
            ;;
        *)
            if [[ "$1" == "all" ]]; then
                DISKS="`ls -l /sys/class/block/ | grep -v -E '(loop)|(ram[0-9]+)|(sr[0-9]+)' | grep -E '/[^/]+$' | awk '{print $9}'`"
                DISKS=(${DISKS[@]})
            elif [[ "$1" =~ ^[a-fA-F0-9]+:[a-fA-F0-9]+\.[a-fA-F0-9]$ ]]; then
                CANDIDATES=`ls -l /sys/class/block/ | grep -v -E '(loop)|(ram[0-9]+)|(sr[0-9]+)' | grep $1 | awk '{print $9}'`
                [[ -z $CANDIDATES ]] && advError "Can not found pcie sata controller: $1" && exit 1
                DISKS=(${DISKS[@]} ${CANDIDATES[@]})
            else
                CANDIDATES=`ls -l /sys/class/block/ | grep -v -E '(loop)|(ram[0-9]+)|(sr[0-9]+)' | grep -i $1 | awk '{print $9}'`
                [[ -z $CANDIDATES ]] && advError "Disk not exist: $1" && exit 1
                DISKS=(${DISKS[@]} ${CANDIDATES[@]})
            fi
            ;;  
    esac    
    shift
done

[[ -z $DISKS ]] && advError "No disk specified!" && exit 1

advInfo "Filtering multipath nvmes: ${DISKS[@]}"
for DISK in ${DISKS[@]}; do
    [[ $DISK =~ nvme[0-9]+c[0-9]+n[0-9]+ ]] && continue
    TARGETS=(${TARGETS[@]} $DISK)
done
advInfo "Filtered multipath nvmes: ${TARGETS[@]}"

DISKS=(${TARGETS[@]})
unset TARGETS
advInfo "Filtering disks with partition: ${DISKS[@]}"
for DISK in ${DISKS[@]}; do
    DEVICE=`echo $DISK | grep -oE '(^md[0-9]+|^nvme[0-9]+n[0-9]+|^[a-z]+|^pmem[0-9]+)'`
    echo "${TARGETS[@]}" | grep -qw $DEVICE
    [[ $? -eq 0 ]] && continue
    PART=`ls -l /sys/class/block/ | grep -v -E '(loop)|(ram[0-9]+)|(sr[0-9]+)' | grep devices | awk '{print $9}' | grep -oE "$DISK(p?)[0-9]" | tr '\n' ' ' | sed 's/ $//'`
    [[ -z $PART ]] && TARGETS=(${TARGETS[@]} $DISK) && continue
    advInfo "Using partition(s) '${PART[@]}' to replace '$DISK'"
    TARGETS=(${TARGETS[@]} ${PART[@]})
done

DISKS=(${TARGETS[@]})
unset TARGETS
advInfo "Filtering duplicated disks: ${DISKS[@]}"
for DISK in ${DISKS[@]}; do
    echo "${TARGETS[@]}" | grep -qw $DISK
    [[ $? -eq 0 ]] && continue
    TARGETS=(${TARGETS[@]} $DISK)
done
advInfo "Filtered duplicated disks: ${TARGETS[@]}"

advIsRootFS() {
    local DEVICE=`echo $1 | grep -oE '(^md[0-9]+|^nvme[0-9]+n[0-9]+|^[a-z]+|^pmem[0-9])'`
    grep -w '/' /proc/mounts | grep -qw live
    if [[ $? -eq 0 ]]; then
        advInfo "Live-cd OS detected"
        grep $DEVICE /proc/mounts | grep -qw live
        return $?
    fi

    grep -w '/' /proc/mounts | grep -q $DEVICE
    return $?
}

if [[ -z $THIS_ANY_DEVICE ]]; then
    DISKS=(${TARGETS[@]})
    unset TARGETS
    advInfo "Filtering mounted root fs: ${DISKS[@]}"
    for DISK in ${DISKS[@]}; do
        advIsRootFS $DISK
        if [[ $? -eq 0 ]]; then
        DEVICE=`echo $DISK | grep -oE '(^md[0-9]+|^nvme[0-9]+n[0-9]+|^[a-z]+|^pmem[0-9])'`
        TARGETS=(${TARGETS[@]/$DEVICE})
            advNotice "Removing mounted root fs: $DISK"
        else
            TARGETS=(${TARGETS[@]} $DISK)
            continue
        fi
    done
    advInfo "Filtered without mounted root fs: ${TARGETS[@]}"
fi

[[ -z $TARGETS ]] && advError "No disk to test!" && exit 1

[[ -n $THIS_KB ]] && SU='KB' || SU='MB'

advInfo "Target device: ${TARGETS[@]}"

advClean() {
    [[ -f $THIS_SOURCE_FILE ]] && rm -rf $THIS_SOURCE_FILE
    [[ -f $SOURCE_FILE ]] && rm -rf $SOURCE_FILE
    [[ -n $TARGET_FILES ]] && rm -rf ${TARGET_FILES[@]} 2>/dev/null
    for MOUNT in ${MOUNTED[@]}; do
        advInfo "Umounting $MOUNT ..."
        umount $MOUNT >/dev/null 2>&1
        rm -rf $MOUNT
    done
}

advCleanExit() {
    advNotice "Cleaning and exiting ..."
    advClean
    [[ -z $1 ]] && exit 0
    exit $1
}

advEvalKey() {
    VAR_NAME="$1"
    KEY="$2"
    KEY=${KEY//-/_}
    eval $VAR_NAME=\$${VAR_NAME}_${KEY}
}

advEvalValue() {
    VAR_NAME="$1"
    KEY="$2"
    KEY=${KEY//-/_}
    eval ${VAR_NAME}_${KEY}=$3
}

advShowResult() {
    [[ -z $DISK_RW_STARTED ]] && advNotice "Real testing not started" && exit 1
    advNotice "Checking result ..."
    for DISK in ${DISKS[@]}; do
        advEvalKey TOTAL_COUNT "$DISK"
        advEvalKey FAILED_COUNT "$DISK"
        
        if [[ $FAILED_COUNT -gt 0 ]]; then
            advNotice "Run $TOTAL_COUNT at $DISK but failed $FAILED_COUNT"
            FAILED_ITEMS=(${FAILED_ITEMS[@]} "$DISK")
        elif [[ $TOTAL_COUNT -gt 0 ]]; then
            advInfo "Run $TOTAL_COUNT at $DISK without failure"
            PASSED_ITEMS=(${PASSED_ITEMS[@]} "$DISK")
        else
            advNotice "Run $TOTAL_COUNT at $DISK"
            FAILED_ITEMS=(${FAILED_ITEMS[@]} "$DISK")
        fi
    done
    
    [[ -n $PASSED_ITEMS ]] && advInfo "[PASSED ITEMS] [$ADV_TEST_ITEM] [${PASSED_ITEMS[@]}]"
    [[ -z $FAILED_ITEMS ]] && advPassed "[$ADV_TEST_ITEM]" && exit 0
    
    advNotice "[FAILED ITEMS] [$ADV_TEST_ITEM] [${FAILED_ITEMS[@]}]"
    advFailed "[$ADV_TEST_ITEM]"
    exit 1
}

advTrap "advClean; advShowResult"

advGenerateFile() {
    local DEVICE=$1
    local FILE=$2
    local SIZE=$3
    if [[ -n $THIS_KB ]]; then
        advInfo "dd if=$DEVICE of=$FILE bs=1K count=$SIZE"
        dd if=$DEVICE of=$FILE bs=1K count=$SIZE >/dev/null 2>&1
        [[ $? -ne 0 ]] && advNotice "Failed to generate ${SIZE}KB file '$FILE' from $DEVICE" && return 1
        [[ ! -f $FILE ]] && advNotice "File '$FILE' not exist" && return 1
        ACT_SIZE=`ls -l --block-size=K $FILE | awk '{print $5}'`
        ACT_SIZE=${ACT_SIZE%K}
        [[ $ACT_SIZE -ne $SIZE ]] && advNotice "Size of file '$FILE' ${ACT_SIZE}KB not match ${SIZE}KB" && return 1
    else
        advInfo "dd if=$DEVICE of=$FILE bs=1M count=$SIZE"
        dd if=$DEVICE of=$FILE bs=1M count=$SIZE >/dev/null 2>&1
        [[ $? -ne 0 ]] && advNotice "Failed to generate ${SIZE}MB file '$FILE' from $DEVICE" && return 1
        [[ ! -f $FILE ]] && advNotice "File '$FILE' not exist" && return 1
        ACT_SIZE=`ls -l --block-size=M $FILE | awk '{print $5}'`
        ACT_SIZE=${ACT_SIZE%M}
        [[ $ACT_SIZE -ne $SIZE ]] && advNotice "Size of file '$FILE' ${ACT_SIZE}MB not match ${SIZE}MB" && return 1
    fi
    
    return 0
}

SOURCE_PATHS=(/dev/shm /tmp)
[[ -n $THIS_SOURCE_PATH ]] && SOURCE_PATHS=($THIS_SOURCE_PATH ${SOURCE_PATHS[@]})

advInfo "Finding valid source patch: ${SOURCE_PATHS[@]}"
for SOURCE_PATH in ${SOURCE_PATHS[@]}; do
    advInfo "Trying generate ${THIS_FILE_SIZE}${SU} source file in $SOURCE_PATH ..."
    THIS_SOURCE_FILE=$SOURCE_PATH/adv.$$.disk.source
    advGenerateFile /dev/zero $THIS_SOURCE_FILE $THIS_FILE_SIZE
    [[ $? -eq 0 ]] && break
    [[ -f $THIS_SOURCE_FILE ]] && rm -rf $THIS_SOURCE_FILE
done

if [[ ! -f $THIS_SOURCE_FILE ]]; then
    advError "Can not find a path to generate source file ..." && advCleanExit 1
fi
rm -rf $THIS_SOURCE_FILE

DISKS=(${TARGETS[@]})

if [[ -n $THIS_KB ]]; then
    REQUIRED_SIZE=$(($THIS_FILE_SIZE * ( $THIS_DUPLICATE + 1 ) * 110 / 100000 + 100))
else
    REQUIRED_SIZE=$(($THIS_FILE_SIZE * ( $THIS_DUPLICATE + 1 ) * 110 / 100 + 100))
fi
unset TARGETS
unset MOUNTED
advInfo "Checking disks mounted or mountable with required ${REQUIRED_SIZE}{$SU}: ${DISKS[@]}"
for DISK in ${DISKS[@]}; do
    DEVICE=`echo $DISK | grep -oE '(^md[0-9]+|^nvme[0-9]+(c[0-9]+)?n[0-9]+|^[a-z]+|^pmem[0-9]+)'`
    echo "${VERIFIED_DEVICES[@]}" | grep -qw $DEVICE
    [[ $? -eq 0 ]] && advInfo "Already found partition for $DEVICE, ignore $DISK!" && continue
    echo "${ALL_DEVICES[@]}" | grep -qw $DEVICE
    [[ $? -ne 0 ]] && ALL_DEVICES=(${ALL_DEVICES[@]} $DEVICE)

    MOUNT=`mount | grep -E "^[^ ]+$DISK" | awk '{print $3}'`
    if [[ -n $MOUNT ]]; then
        advInfo "$DISK already mounted, using '$MOUNT' to test writable"
    else
        LVM=`lsblk -l | grep $DISK | awk '{print $6}'`
        [[ "$LVM" == "lvm" ]] && DEV=/dev/mapper/$DISK || DEV=/dev/$DISK
        MOUNT=/tmp/adv.$$.mount.$DISK
        mkdir -p $MOUNT
        MOUNTED=(${MOUNTED[@]} $MOUNT)
        advInfo "Try to mount '$DEV' to '$MOUNT' ..."
        mount $DEV $MOUNT
        df | grep -qi $MOUNT
        [[ $? -ne 0 ]] && advNotice "Failed to mount '$DEV' to '$MOUNT'" && continue
    fi
    TEST_TMP=$MOUNT/adv.$$.tmp.$DISK
    touch $TEST_TMP
    [[ ! -f $TEST_TMP ]] && advNotice "'$MOUNT' is not writable!" && continue
    rm -rf $TEST_TMP
    [[ -f $TEST_TMP ]] && advNotice "'$MOUNT' is not writable!" && continue
    REST=`df -m $MOUNT | tail -n 1 | awk '{print $4}'`
    REST=${REST%M}
    if [[ $REST -lt $REQUIRED_SIZE ]]; then
        advNotice "No enough free space in '$MOUNT($DISK)', only ${REST}MB, required ${REQUIRED_SIZE}MB, ignore it!"
        continue
    fi
    TARGETS=(${TARGETS[@]} $MOUNT)
    VERIFIED=(${VERIFIED[@]} $DISK)
    advEvalValue FAILED_COUNT "$DISK" 0
    advEvalValue TOTAL_COUNT "$DISK" 0
    advInfo "Using partition $DISK for $DEVICE"
    VERIFIED_DEVICES=(${VERIFIED_DEVICES[@]} $DEVICE)
    unset MOUNT
done
[[ ${#VERIFIED_DEVICES[@]} -ne ${#ALL_DEVICES[@]} ]] && advError "Some devices not mountable, writable or less free space" && advCleanExit 1
DISKS=(${VERIFIED[@]})

for DEVICE in ${TARGETS[@]}; do
    echo "${VERIFIED_DEVICES[@]}" | grep -qw $DEVICE
    [[ $? -eq 0 ]] && continue
    advNotice "No found valid or usable partition for $DEVICE!"
    
    if [[ -n $THIS_MAKE_PART ]]; then
        LVM=`lsblk -l | grep $DEVICE | awk '{print $6}'`
        [[ -z $THIS_MAKE_PART || "$LVM" == "lvm" ]] && continue
        advIsRootFS $DEVICE
        if [[ $? -eq 0 ]]; then
            advInfo "$DEVICE is mounted and no touchable!"
            continue
        fi
        
        [[ -n $MOUNT ]] && umount $MOUNT
        if [[ -z $THIS_FORCE ]]; then
            unset YN
            while [[ -z $YN ]]; do
                advNotice "Will try to destroy current partitions on /dev/$DEVICE, all exist data will lost, are you sure? (y/n)"
                read YN
                if [[ "$YN" == "y" || "$YN" == "Y" ]]; then
                    advInfo "User confirmed: $YN"
                    break
                elif [[ "$YN" == "n" || "$YN" == "N" ]]; then
                    advInfo "User rejected: $YN"
                    exit 1
                fi
            done
        fi
        
        if [[ -n $THIS_KB ]]; then
            PART_SIZE=$(($REQUIRED_SIZE * 110 / 100000 + 100))
        else
            PART_SIZE=$(($REQUIRED_SIZE * 110 / 100 + 100))
        fi
        advNotice "Try to make new partition with ${PART_SIZE}MB on $DEVICE"
        advRunLog parted -s /dev/$DEVICE -- mklabel msdos mkpart primary ext${THIS_FILETYPE} 0 ${PART_SIZE}MiB
        [[ $? -ne 0 ]] && advNotice "Failed to make new partition on $DEVICE, ignore it!" && continue
        partprobe /dev/$DEVICE
        [[ $DEVICE =~ nvme || $DEVICE =~ pmem ]] && DISK=${DEVICE}p1 || DISK=${DEVICE}1
        DEV=/dev/$DISK
        advNotice "Detecting new partition $DEV on $DEVICE ..."
        for ((W=0; W<10; W++)); do
            [[ -n $DEV ]] && break
            sleep 1
        done
        [[ -z $DEV ]] && advNotice "Failed to create $DEV, ignore it!" && continue
        advNotice "Partition $DEV created, now formatting file system ..."
        advRunLog mkfs -t ext${THIS_FILETYPE} $DEV
        [[ $? -ne 0 ]] && advNotice "Failed to make fs on $DEV, ignore it!" && continue
        
        MOUNT=/tmp/adv.$$.mount.$DISK
        mkdir -p $MOUNT
        MOUNTED=(${MOUNTED[@]} $MOUNT)
        advInfo "Try to mount '$DEV' to '$MOUNT' ..."
        mount $DEV $MOUNT
        df | grep -qi $MOUNT
        [[ $? -ne 0 ]] && advNotice "Failed to mount new partition '/dev/$DISK' to '$MOUNT'" && continue
        
        TARGETS=(${TARGETS[@]} $MOUNT)
        VERIFIED=(${VERIFIED[@]} $DISK)
        advEvalValue FAILED_COUNT "$DISK" 0
        advEvalValue TOTAL_COUNT "$DISK" 0
        advInfo "Using partition $DISK for $DEVICE"
        VERIFIED_DEVICES=(${VERIFIED_DEVICES[@]} $DEVICE)
        unset MOUNT
    fi

done

[[ -z $TARGETS ]] && advError "No partition to test!" && advCleanExit 1

[[ ${#VERIFIED_DEVICES[@]} -ne ${#TARGETS[@]} ]] && advError "Some devices not testable" && advCleanExit 1

advRunLog df

[[ $THIS_LOOP -eq 0 ]] && THIS_LOOP_STRING=infinite || THIS_LOOP_STRING=$THIS_LOOP
if [[ -z $THIS_TIME_TO_RUN ]]; then
    advInfo "Running ${THIS_LOOP_STRING}x${THIS_DUPLICATE}x${THIS_READ} times on: ${TARGETS[@]}"
else
    advInfo "Running ${THIS_LOOP_STRING}x${THIS_DUPLICATE}x${THIS_READ} times within ${THIS_TIME_TO_RUN}s on: ${TARGETS[@]}"
fi

[[ -n $THIS_TIME_TO_RUN ]] && START_TIME=`date +%s`

DISK_RW_STARTED=1
SOURCE_DEVICE=/dev/zero
SOURCE_TYPE="zero"
if [[ -n $THIS_RANDOM_FILE ]]; then
    SOURCE_DEVICE=/dev/urandom
    SOURCE_TYPE="random"
fi
for (( L=0; ; L++ )); do
    [[ $L -ge $THIS_LOOP && $THIS_LOOP -ne 0 ]] && break
    advInfo "Round $((L+1)): Generating ${THIS_FILE_SIZE}${SU} source file by $SOURCE_TYPE ..."
    SOURCE_FILE=$THIS_SOURCE_FILE.$((L+1))
    advGenerateFile $SOURCE_DEVICE $SOURCE_FILE $THIS_FILE_SIZE
    if [[ $? -ne 0 ]]; then
        advNotice "Something wrong when generating source file, waiting 5 seconds ..."
        sleep 5
        continue
    fi
    SOURCE_MD5=`md5sum $SOURCE_FILE | cut -d ' ' -f 1`
    
    unset TARGET_FILES
    for (( D=0; D<$THIS_DUPLICATE; D++ )); do
        for (( T=0; T<${#TARGETS[@]}; T++ )); do
            DISK=${DISKS[$T]}
            MOUNT=${TARGETS[$T]}
            TARGET_FILE=$MOUNT/adv.$$.target.$DISK.$((L+1)).$((D+1))
            advEvalKey TOTAL_COUNT "$DISK"
            TOTAL_COUNT=$(($TOTAL_COUNT + 1))
            advEvalValue TOTAL_COUNT "$DISK" $TOTAL_COUNT
    
            advInfo "Round $((L+1))-$((D+1)): Copying '$SOURCE_FILE' to '$TARGET_FILE' ..."
            TARGET_FILES=(${TARGET_FILES[@]} $TARGET_FILE)
            cp $SOURCE_FILE $TARGET_FILE
            [[ -z $THIS_KB ]] && sync
            [[ $THIS_READ -gt 1 ]] && advInfo "Round $((L+1))-$((D+1)): Reading '$TARGET_FILE' $THIS_READ times ..."
            for (( R=0; R<$THIS_READ; R++ )); do
                TARGET_MD5=`md5sum $TARGET_FILE | cut -d ' ' -f 1`
                
                if [[ "$TARGET_MD5" != "$SOURCE_MD5" ]]; then
                    advInfo "Round $((L+1))-$((D+1))-$((R+1)): $DISK($MOUNT) not match $TARGET_MD5 != $SOURCE_MD5"
                    advEvalKey FAILED_COUNT "$DISK"
                    FAILED_COUNT=$(($FAILED_COUNT + 1))
                    advEvalValue FAILED_COUNT "$DISK" $FAILED_COUNT
                fi
            done
        done
    done
        
    rm -rf $SOURCE_FILE
    rm -rf ${TARGET_FILES[@]}
    
    if [[ -n $THIS_TIME_TO_RUN ]]; then
        CURRENT_TIME=`date +%s`
        DIFF=$(($CURRENT_TIME - $START_TIME))
        if [[ $DIFF -ge $THIS_TIME_TO_RUN ]]; then
            advNotice "Run $((L+1)) rounds in ${DIFF}s, time reach ${THIS_TIME_TO_RUN}s, stopping ..."
            break
        fi
    fi

    [[ $THIS_INTERVAL -gt 0 ]] && advInfo "Round $((L+1)): Waiting $THIS_INTERVAL second(s) ..." && sleep $THIS_INTERVAL
done

advNoTrap

advClean
advShowResult
